### PR TITLE
openai[minor]: OpenAI - Ability to set stream_options and streamUsage when instantiating ChatOpenAI class.

### PR DESCRIPTION
**Pull request by deranga**
Fixes [965](https://github.com/langchain-ai/langchainjs/issues/965) - Where its not possible to get the usage back from OpenAI when streaming and using chains or agents.

### CODE REVIEW

**Review by bracesproul — CHANGES_REQUESTED** [review]
hey, thanks for taking initiative on this! We're actually implementing a new `streamUsage` constructor arg & call option, but haven't gotten around to implementing it for OpenAI yet. If you wanted to implement it, [here's a PR](https://github.com/langchain-ai/langchainjs/pull/5730/files) you can copy from. If not, feel free to close this PR.

Please ping me if you have any questions on it!

**Comment by bracesproul** [comment]
Actually, lets include both `streamOptions: { includeUsage: boolean }` (prefer camel case for our API) and `streamUsage: boolean`. OAI might add more fields to their `stream_options` API in the future, in which case we'd like a way to support those too!

**Comment by deranga** [comment]
@bracesproul, I think I've made the changes you are after. 

I have a separate, but related question around embeddings token usage, happy to ask this in a separate issue.... The core langchainjs package has types that prevent returning metadata around the embedding response, and ideally from pov it would allow exposing the token usage if the integration supported it. Do you know if there are any plans to make it possible to access token usage from embeddings requests?

**Comment by deranga** [comment]
@bracesproul, I've reviewed the PR for anthropic with streamUsage,  and updated this PR to include it for OpenAI.

I think the interface at the moment is a little strange as currently one of either stream_options or streamUsage would have to take precedence? For now I've made it that stream_options takes precedence if set, but this might lead to odd behaviour for users of the library?

Any input would be appreciated on how you want this to proceed.

**Comment by deranga** [comment]
@jacoblee93, this is the PR you suggested in #965 alongside the streamUsage addition suggested above. Do let me know if there are any changes needed?

**Comment by jacoblee93** [comment]
Hey! So sorry will look tomorrow!

**Comment by deranga** [comment]
Want me to update the tests?

**Comment by jacoblee93** [comment]
Getting a few 400s when running integration tests:

```
400 The 'stream_options' parameter is only allowed when 'stream' is enabled.
```

Seems like we may need to be a bit more selective on how we populate this?

**Comment by deranga** [comment]
Is it possible to run the integration tests outside of being kicked off by a maintainer?

To address the 400 for stream: false when requesting usage data I've updated so that either stream_options: {include_usage:true}/ streamUsage true will force the stream flag to be set to true, and if not fallback to this.streaming. To make it BC I've altered streamUsage to default to false

**Comment by jacoblee93** [comment]
Changed to default to true, avoid passing as an invocation param if `this.streaming` is false.

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
