### PR TITLE
Docs[patch]: npm i guide issue in sql docs

### PR DESCRIPTION
**Pull request by FrankenDeba**
https://js.langchain.com/docs/use_cases/sql/quickstart

### CODE REVIEW

**Comment by FrankenDeba** [comment]
Place for the issue: https://js.langchain.com/docs/use_cases/sql/quickstart

**Comment by FrankenDeba** [comment]
@jacoblee93 Can you check why the docs build is failing?
I am not able to open vercel!

**Comment by FrankenDeba** [comment]
image

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
