### PR TITLE
add delete for faiss

### LINKED ISSUE #2427: Delete/upsert support in FAISS
We've had a request for better delete/upsert support for the FAISS store - @ewfian would you be able to tackle adding it to the underlying package?

https://twitter.com/vsrisaijyothi/status/1696054437348069807?s=20

### PR DESCRIPTION
**Pull request by ewfian**
Fixes #2427

Also ports https://github.com/langchain-ai/langchain/pull/5190
Also fixes [float64 parsing](https://github.com/ewfian/pickleparser/commit/bbeb7a23c9cb43f798e1a64975a49e3463e1054a#diff-f001cb9a1f05bafde7fad2a8ee1f61e63fde31a7ab69119ccb8405a0a79b6e3aL100) by upgrade pickleparser

relates: https://github.com/langchain-ai/langchain/issues/2699

### CODE REVIEW

**Comment by ewfian** [comment]
this CI failed with OOM, it should be passed with rerun.

**Comment by jacoblee93** [comment]
Awesome, thank you!

I'll add a docs page and fix CI later.

**Comment by jacoblee93** [comment]
Hey @ewfian, I think there's a bug - when I tried to run the example I added I got:

`Error: Could not load example examples/src/indexes/vector_stores/faiss_delete.ts: Error: ID undefined not found.`

Can you have a look and see if you can repro?

**Comment by ewfian** [comment]
@jacoblee93 Thank you for adding docs, the bug was fixed.

**Comment by jacoblee93** [comment]
You rock, thanks!

**Pull request merged**
