### PR TITLE
feat(mistral): Mistral 1.3.1 migration

### PR DESCRIPTION
**Pull request by CarterMorris**
This PR updates the Mistral AI integration from version 0.4.0 to version 1.3.1. It includes fixing the outdated functionality of the Mistral chat models, embeddings, and llms integrations, as well as adding support for new features introduced to Mistral such as new model parameters, complex message types, and hooks. The Mistral integration of messages has been updated to support both Langchain's MessageContentComplex and Mistral's ContentChunk, with all necessary conversions. New unit and integration tests were added to test the new functionality, and the Mistral documentation was updated to include information on how to use hooks.

The migration was taken over from [this PR](https://github.com/langchain-ai/langchainjs/pull/6514).

### CODE REVIEW

**Comment by CarterMorris** [comment]
Hey @jacoblee93, we've completed the Mistral migration to version 1.3.1, ready for review at your earliest convenience! Thanks

**Comment by jacoblee93** [comment]
Thank you @CarterMorris! Will look soon.

CC @ sophiamyang

**Review by jacoblee93 — APPROVED** [review]
Overall this looks fantastic, thank you so much!

**Comment by jacoblee93** [comment]
Thank you all!

**Pull request merged**
