### PR TITLE
community[minor]: Spider Document Loader

### PR DESCRIPTION
**Pull request by WilliamEspegren**
Added the [Spider](https://spider.cloud/) document loader. Spider scrapes/crawls a domain following all subpages and return llm-ready data.

This integration is already in the python version ([github PR here](https://github.com/langchain-ai/langchain/pull/20937))

`Twitter: @WilliamEspegren`

Thank you :)

PR inspired by [this PR](https://github.com/langchain-ai/langchainjs/pull/5180)

### CODE REVIEW

**Review by bracesproul — DISMISSED** [review]
Thanks for putting this up! It's a little confusing, but we've deprecated adding document loaders in `langchain` and have instead moved them to `@langchain/community`

Could you push up a commit removing the code from `langchain` and moving it to `@langchain/community`? Thanks a lot!

**Comment by WilliamEspegren** [comment]
I can do it in 10 minutes, it should be the exact same code right? Just in another place? @bracesproul

**Comment by bracesproul** [comment]
> I can do it in 10 minutes, it should be the exact same code right? Just in another place? @bracesproul 

Yes!

**Comment by WilliamEspegren** [comment]
> > I can do it in 10 minutes, it should be the exact same code right? Just in another place? @bracesproul
> 
> Yes!

Now I believe that I have it correct

**Comment by WilliamEspegren** [comment]
@bracesproul 🎉🎉 the checks are passing

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
