### PR TITLE
Updated debugging.mdx

### LINKED ISSUE #4318: Bug in documentation usage of<CodeOutputBlock> instead of <CodeBlock>
There's a bug in the documentation, specifically in [docs/core_docs/docs/guides/debugging.mdx](https://github.com/langchain-ai/langchainjs/blob/main/docs/core_docs/docs/guides/debugging.mdx). I have a fix and a PR ready. I am creating this issue to I can reference the PR

### PR DESCRIPTION
**Pull request by jasonnathan**
Fixes #4318

### CODE REVIEW

**Comment by jasonnathan** [comment]
<CodeBlock> specifically references internal imports when parsing an @examples/.ts file. In this case, the usage of <CodeBlockOutput> I think was intended to display outputs like logs but it isn't defined anywhere so I change it to ```typescript```. I can change it to ```plaintext``` if this is preferred

**Review by bracesproul — APPROVED** [review]
Thank you for adding this!

**Comment by jasonnathan** [comment]
I think you made the changes already?

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
