### PR TITLE
google-common[patch]: Zod to Gemini params conversion when the schema contains arrays of items

### PR DESCRIPTION
**Pull request by miguelff**
This PR adds, in separate commits, a failing test demonstrating that zod schemas containing arrays leak the `additionalProperties` key into the resulting JSON schema; and a fix for it. 

The bug made Gemini's API bail out with a message similar to the following:

```
...
 {
    error: {
      code: 400,
      message: `Invalid JSON payload received. Unknown name "additionalProperties" at 'tools[0].function_declarations[0].parameters.properties[0].value.items': Cannot find field.`,
      errors: [Array],
      status: 'INVALID_ARGUMENT',
      details: [Array]
    }
}
```

The patch walks the _dirty_ json schema to find and delete `additionalProperties` into the `items` keys as well.

### CODE REVIEW

**Comment by afirstenberg** [comment]
Good catch!

Is it iterating over the items in the array clearing them out? Not clear to me from the code that it is.

(As an aside, can you change the title so something like "google-common [patch]: Zod to Gemini params conversion when schema contains arrays", please?)

**Comment by jacoblee93** [comment]
Hey, am actually having some issues getting Gemini to call tools at all at the moment - either of you experiencing this?

**Comment by jacoblee93** [comment]
Tool calling issue fixed in #5571, will now merge this to fix this second issue. Thank you for reporting!

**Comment by jacoblee93** [comment]
CI is having issues, it passed lint this time so merging!

**Comment by miguelff** [comment]
@jacoblee93 I was indeed having issues and was planning to investigate and fix today. I've seen the patch for the streaming responses, will use latest changes and reassess. 

I will report new issues / PRs in case I still see anything wrong.

**Pull request merged**
