### PR TITLE
langchain[minor]: Date Output Parser

### LINKED ISSUE #2873: Add a Date Output Parser
**Feature request**
Output parser which takes a language model response and parses it into a Date object 

**Motivation**
Aside from the fact that the DateTime parser already exists in the Python version, adding this parser will make querying and interacting with dates more streamlined and easier

**Your contribution**
Me and a small group will work on creating a PR

### PR DESCRIPTION
**Pull request by jeffbuyunhe**
Closes #2873
Added the Date Output parser, parsing LLM output into a Date object via converting it to an ISO8601 date time string.

Willing to provide documentation once its been merged.

Please leave feedback below, this is my first contribution.

This feature is similar to the Python version with docs [here](https://python.langchain.com/docs/modules/model_io/output_parsers/types/datetime).

Tested manually.

### CODE REVIEW

**Comment by jeffbuyunhe** [comment]
[Relevant issue](https://github.com/langchain-ai/langchainjs/issues/2873)

**Review by bracesproul — CHANGES_REQUESTED** [review]
This all looks really good! A few comments:
1. could you remove from the `langchain/` directory and move into `langchain-core/`? We've deprecated adding new integrations/features to `langchain`, with a few exceptions (chains, agents etc).
2. if you could add docs to this PR it would make the review/merge process easier, that way we could merge all at once.

**Comment by jeffbuyunhe** [comment]
Hey sorry meant to get to this earlier, but I spent the past two days resting because of COVID, just curious though, from Jacob's commits it seems like he kept the parser in `langchain/`, and did not move it into `langchain-core/`, is there a reason for that?

**Comment by jacoblee93** [comment]
Ah hope you're feeling ok :(

Yes, Brace was mistaken. Some things still belong in LangChain.

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
