### PR TITLE
community[patch]: Add support for exists filter in the elasticsearch vector store.

### PR DESCRIPTION
**Pull request by joachimvandenabeele**
This PR adds support for filtering with "exists" for the elasticsearch vector store.

### CODE REVIEW

**Comment by jacoblee93** [comment]
LGTM, thanks!

**Comment by jacoblee93** [comment]
Hey @joachimvandenabeele, could you run `yarn format` to get CI passing? I can't push to your branch.

**Comment by jacoblee93** [comment]
Thank you!

**Comment by joachimvandenabeele** [comment]
My pleasure!

**Pull request merged**
