### PR TITLE
community[minor]: feat: QdrantTranslator for self-query retrieval

### PR DESCRIPTION
**Pull request by Anush008**
## Description

This PR adds a new `QdrantTranslator` class for using `SelfQueryRetriever` with the Qdrant vector store.

P.S. It's 400 lines of test code, 200 lines of doc. The implementation is about 200 lines. Please do take a look.

### CODE REVIEW

**Comment by jacoblee93** [comment]
Seems fine overall - could you add some docs?

**Comment by Anush008** [comment]
Pushed the docs to this PR as suggested.

**Comment by jacoblee93** [comment]
Thank you!

**Comment by jacoblee93** [comment]
Thank you! We are moving all of these translators to `@langchain/community` in 0.2, so just going to put it here to get a head start on it.

**Pull request merged**
