### PR TITLE
fix(community): Migrate xenova transformers lib to huggingface

### PR DESCRIPTION
**Pull request by PylotLight**
Fixes # (issue)
- Update all xenova npm pkg references to huggingface and update lib version to latest.
- Noting I have tested building which worked successfully for me after reference changes were made.

I tested the build with the following dockerfile for reference:
```docker
FROM node:18-slim
WORKDIR /usr/src
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    git \
    build-essential \
    python3 \
    python3-pip \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN corepack enable \
 && corepack prepare yarn@3.4.1 --activate

COPY . .

WORKDIR /usr/src/libs/langchain-community
RUN yarn

WORKDIR /usr/src/langchain-core
RUN yarn && yarn build

WORKDIR /usr/src/app
CMD ["/bin/bash"]
```

image

### CODE REVIEW

**Comment by PylotLight** [comment]
I didn't touch docs, not sure why that check is failing and if there's anything I can do about it. I can't see logs of what the issue is either.

**Review by jacoblee93 — COMMENTED** [review]
Thanks for this!

Would be nice to have some kind of fallback so that it fails gracefully for people using the old package - can take over and look into it!

**Comment by PylotLight** [comment]
> Thanks for this!
> 
> Would be nice to have some kind of fallback so that it fails gracefully for people using the old package - can take over and look into it!

Please do!
Let me know if there's anything I can help with.

**Comment by jacoblee93** [comment]
Hey @PylotLight - given how finicky bundlers can be I think it's safer to just make it a new entrypoint and deprecate the old one

I've done that here. Will merge and ship tonight or tomorrow!

**Comment by PylotLight** [comment]
> Hey @PylotLight - given how finicky bundlers can be I think it's safer to just make it a new entrypoint and deprecate the old one
> 
> I've done that here. Will merge and ship tonight or tomorrow!

Love it!
Thank you for pushing this =]

**Pull request merged**
