### PR TITLE
Update `firebase-admin` dependency

### LINKED ISSUE #4376: Bump `firebase-admin@^12.0.0` dependency
Bump version of firebase-admin

### PR DESCRIPTION
**Pull request by JakubKontra**
Bump firebase-admin dependency

Fixes #4376

### CODE REVIEW

**Comment by jacoblee93** [comment]
Thank you! Any breaking changes that would affect the integration here?

**Comment by jacoblee93** [comment]
Actually, if there are no breaking changes - can you update the peer dep to:

```
^11.9.0 || ^12.0.0
```

To avoid breaking build?

**Comment by JakubKontra** [comment]
@jacoblee93
No breaking changes there, updated to `^11.9.0 || ^12.0.0`.
Thanks!

**Comment by jacoblee93** [comment]
Thank yoU!

**Pull request merged**
