### PR TITLE
community[patch]: Add support for inner product and Euclidean distance to `PGVector`

### PR DESCRIPTION
**Pull request by andrewnguonly**
### Summary
Add support for inner product and Euclidean distance to `PGVector`. The implementation is modeled after the `CassandraStore` implementation.

### To Do
- [ ] Figure out how to run `PGVector` tests.
- [x] Update [LangChain's PGVector documentation](https://js.langchain.com/docs/integrations/vectorstores/pgvector) to indicate that different vector types are supported.

### Future
1. I can probably make this change in the Python library as well.

### References
1. [PGVector Vector Operators](https://github.com/pgvector/pgvector/?tab=readme-ov-file#vector-operators)
2. [Discord thread](https://discord.com/channels/1038097195422978059/1076182741374214285/1217854243017588816)

### CODE REVIEW

**Comment by andrewnguonly** [comment]
I see that the Python implementation uses the naming "distance strategy". I can update this PR to make the naming consistent across both libraries.

**Comment by jacoblee93** [comment]
Yes, consistent naming would be good if you can make that change

**Review by bracesproul — APPROVED** [review]
lgtm, thanks!

**Comment by andrewnguonly** [comment]
Steps to run `PGVector` tests locally.
1. Create fake environment variable for `OPENAI_API_KEY`. `export OPENAI_API_KEY=fake_api_key`.
2. Run `docker-compose up --build` from `libs/langchain-community/src/vectorstores/tests/pgvector`.
3. Run `yarn test:single src/vectorstores/tests/pgvector/pgvector.int.test.ts`. Verify that test for `computeOperatorString` succeeds.

Heads up @bracesproul @jacoblee93, `docker-compose.yml` specifies port `5432` (default Postgres port), but all the configuration in `pgvector.int.test.ts` uses port `5433`. I had to manually change the port configuration to successfully connect to the database. Is this a bug or is there some reason for this mismatch?

**Comment by bracesproul** [comment]
> Steps to run `PGVector` tests locally.
> 
> 1. Create fake environment variable for `OPENAI_API_KEY`. `export OPENAI_API_KEY=fake_api_key`.
> 2. Run `docker-compose up --build` from `libs/langchain-community/src/vectorstores/tests/pgvector`.
> 3. Run `yarn test:single src/vectorstores/tests/pgvector/pgvector.int.test.ts`. Verify that test for `computeOperatorString` succeeds.
> 
> Heads up @bracesproul @jacoblee93, `docker-compose.yml` specifies port `5432` (default Postgres port), but all the configuration in `pgvector.int.test.ts` uses port `5433`. I had to manually change the port configuration to successfully connect to the database. Is this a bug or is there some reason for this mismatch?

Bug, thanks for fixing

**Comment by jacoblee93** [comment]
It's too avoid conflict with any default Postgres instances running but should probably be the default in any public examples.

**Pull request merged**
