### PR TITLE
fix(langchain): Remove circular peer dep in langchain on @langchain/community

### PR DESCRIPTION
**Pull request by jacoblee93**

### CODE REVIEW

**Comment by jsumners-nr** [comment]
When will this be released to npmjs.com?

**Comment by jacoblee93** [comment]
> When will this be released to npmjs.com?

It's live in langchain@0.3.2 and the latest 0.2.x!

**Comment by jsumners-nr** [comment]
This is what I am seeing:

image

**Comment by jacoblee93** [comment]
This PR only applies to `langchain`, core was fixed in 0.3.1.

**Pull request merged**
