### PR TITLE
feat: Google Calendar View/Create Tools

### PR DESCRIPTION
**Pull request by ShaunBaker**
This pull request provides two separate tools that provide the ability for users to interact with a Google Calendar to retrieve and create events in the calendar through input, [building upon a previous PR](https://github.com/langchain-ai/langchainjs/pull/1777)

This has been suitably updated to allow the passing in of a LLM instance into the tools. This has been tested and successfully adds events to and lists events from a Google calendar.

An example of usage has been added, using the OpenAI LLM and the project/example build and run correctly.

### CODE REVIEW

**Comment by jacoblee93** [comment]
Hey @ShaunBaker, looks great overall - thank you for reviving this!

I made a few fixes to the build/callbacks in #2758 - happy to merge that one directly but can merge this one if you pull those changes into this branch.

**Comment by jacoblee93** [comment]
Awesome, thanks!

**Comment by jacoblee93** [comment]
Thank you for your patience!

**Comment by Luisotee** [comment]
Hey @ShaunBaker, I noticed that you guys deleted your fork. There was a pretty good tutorial on setting up the tool that I don't think made it to the langchain repo. Would it be possible to get that back up or to provide me with the raw markdown and gifs so I can host it myself? Thanks very much for the tool!

By the way, the tutorial was located at: https://github.com/nearform/langchain-google-calendar/blob/master/docs/setup.md

**Comment by simoneb** [comment]
@Luisotee we restored it.

**Pull request merged**
