### PR TITLE
update sql_utils: add oracle integration

### PR DESCRIPTION
**Pull request by matheus-santos-souza**
Implementing support for querying an Oracle database in the SQL DB Querying functionality. Now, the application is capable of efficiently interacting with Oracle databases, thus expanding a range of options for users when performing database queries.

### CODE REVIEW

**Comment by jacoblee93** [comment]
Seems reasonable - please remember to run `yarn lint` and `yarn format`!

**Comment by matheus-santos-souza** [comment]
After some tests on a project at the company where I work using generate query SQL with Oracle, it worked perfectly. I'm new here, I would like some guidance on the next step to complete this integration and start using it in the official library! 😄

**Comment by jacoblee93** [comment]
Sorry, pressed close by accident!

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
