### PR TITLE
feat(community): Add Origin/langchain to Apify's client's user-agent to attribute API activity to langchainhs

### PR DESCRIPTION
**Pull request by jirispilka**
- Add Origin/langchain to Apify's client's user-agent to attribute API activity to LangChain (at Apify, we aim to monitor our integrations to evaluate whether we should invest more in the LangChainjs integration regarding functionality and content).
- Fix issues in documentation (and improve content)

### CODE REVIEW

**Review by jacoblee93 — APPROVED** [review]
LGTM, thanks!

**Comment by jacoblee93** [comment]
Something is wrong in the example you added:

```
Error: src/document_loaders/apify_dataset_existing.ts(19,20): error TS2304: Cannot find name 'ApifyDatasetLoader'.
Error: src/document_loaders/apify_dataset_existing.ts(20,28): error TS7006: Parameter 'item' implicitly has an 'any' type.
Error:  command finished with error: command (/home/runner/work/langchainjs/langchainjs/examples) /tmp/xfs-2e16cf95/yarn run build exited (2)
Error: examples#build: command (/home/runner/work/langchainjs/langchainjs/examples) /tmp/xfs-2e16cf95/yarn run build exited (2)
```

Can you have a look?

**Comment by jirispilka** [comment]
> Something is wrong in the example you added:
> 
> ```
> Error: src/document_loaders/apify_dataset_existing.ts(19,20): error TS2304: Cannot find name 'ApifyDatasetLoader'.
> Error: src/document_loaders/apify_dataset_existing.ts(20,28): error TS7006: Parameter 'item' implicitly has an 'any' type.
> Error:  command finished with error: command (/home/runner/work/langchainjs/langchainjs/examples) /tmp/xfs-2e16cf95/yarn run build exited (2)
> Error: examples#build: command (/home/runner/work/langchainjs/langchainjs/examples) /tmp/xfs-2e16cf95/yarn run build exited (2)
> ```
> 
> Can you have a look?

ohh, I'm sorry, I missed an import 🙄 . Fixed. 
Now, the command: ` yarn turbo:command build --filter=examples` runs without errors.

**Comment by jirispilka** [comment]
@jacoblee93 

Thank you for the reviews.

I'm getting these errors in CI:
```
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 0xb9c1f0 node::Abort() [/usr/local/bin/node]
```

```
error @huggingface/gguf@0.1.12: The engine "node" is incompatible with this module. Expected version ">=20". Got "18.20.4"
error Found incompatible module.
```

I believe these are not caused by my changes or is there a way how I can fix it?

**Comment by jacoblee93** [comment]
Will fix thanks for flagging

**Pull request merged**
