### PR TITLE
fix: remove blank space between words when use pdf-loader

### PR DESCRIPTION
**Pull request by ppxu**
Extends #3218

### CODE REVIEW

**Comment by jacoblee93** [comment]
I had a PDF that seemed to need this - see the test case.

There may be some better way to parse the loader output?

**Comment by jacoblee93** [comment]
Ww could make it a config option?

**Comment by ppxu** [comment]
i see, i always use pdf-loader to load chinese pdfs, so this question is very typical
i add a skipBlank option in pdf-loader for needed

**Comment by jacoblee93** [comment]
Thanks for being persistent, will merge #3306 instead to allow potentially for other types of separators.

**Pull request closed without merging**
