### PR TITLE
Use prefixMessages in ChatOpenAI

### LINKED ISSUE #2913: ChatOpenAI does not use perfixMessages in constructor params
`ChatOpenAI` class that's supposed to replace `OpenAIChat` does not use the `prefixMessages` in constructor params

### PR DESCRIPTION
**Pull request by glenchao**
Fixes #2913

### CODE REVIEW

**Comment by jacoblee93** [comment]
Why not just pass a `ChatPromptTemplate`?

**Comment by glenchao** [comment]
> Thanks for the PR! Why not just pass a `ChatPromptTemplate`?

Sorry, still very new to langchainjs... could you elaborate a bit more? I'm just trying to add what OpenAIChat had and is missing here. `prefixMessages` param is current unused.

**Comment by jacoblee93** [comment]
Check out: https://js.langchain.com/docs/modules/model_io/prompts/prompt_templates/#chat-prompt-template

**Comment by glenchao** [comment]
Thanks for the link. I understand chat prompt template, but I'm not sure what you are suggesting that I do with it. 

I'm trying to use the plan and execute agent with the ChatOpenAI model. I found two ways to get a system message to the agent.
1. chat model instantiation with prefix messages (while ChatOpenAI accepts the param, but it doesn't use it like OpenAIChat)
2. create my own planner instead of using the default one so I can supply my own prompt to the llm chain

**Comment by jacoblee93** [comment]
Ah gotcha - option 2 is a better choice for this actually.

We'll be looking into improving our agent docs in general (CC @bracesproul). Going to close this for now.

**Pull request closed without merging**
