### PR TITLE
feat: add ability to select columns from csv to use as metadata

### PR DESCRIPTION
**Pull request by k11q**
# Feat: add functionality to the CSVLoader to be able to set columns as metadata.

I added the docs and implement the function in the CSVLoader class. The usage below would explain how it works.

## Usage, extracting a single column with metadata

Example CSV file:

```csv
hadith_id,chapter_no,hadith_no,chapter,text_ar,text_en,source
91,3,91,Knowledge - كتاب العلم,"حدثنا عبد الله بن محمد... ثم أدها إليه ".","Narrated Zaid bin Khalid Al-Juhani:... for the wolf.",Sahih Bukhari
92,3,92,Knowledge - كتاب العلم,"حدثنا محمد بن العلاء... إلى الله عز وجل.","Narrated Abu Musa:... (Our offending you).",Sahih Bukhari
93,3,93,Knowledge - كتاب العلم,"حدثنا أبو اليمان... وبمحمد صلى الله عليه وسلم نبيا، فسكت.","Narrated Anas bin Malik:... the Prophet became silent.",Sahih Bukhari
```

Example code:

```typescript
import { CSVLoader } from "langchain/document_loaders";
const loader = new CSVLoader(
  "all_hadiths_clean.csv",
  "text_ar",
  ["text_en", "source", "hadith_id", "chapter_no", "hadith_no", "chapter"]
);
const docs = await loader.load();
/*
[
  Document {
    pageContent: 'حدثنا عبد الله بن محمد... ثم أدها إليه ".',
    metadata: {
      text_en: ' Narrated Zaid bin Khalid Al-Juhani:... for the wolf."',
      source: 'Sahih Bukhari',
      hadith_id: '91',
      chapter_no: '3',
      hadith_no: ' 91 ',
      chapter: 'Knowledge - كتاب العلم',
      line: 91
    }
  },
  Document {
    pageContent: 'حدثنا محمد بن العلاء... إلى الله عز وجل.',
    metadata: {
      text_en: ' Narrated Abu Musa:... (Our offending you).',
      source: 'Sahih Bukhari',
      hadith_id: '92',
      chapter_no: '3',
      hadith_no: ' 92 ',
      chapter: 'Knowledge - كتاب العلم',
      line: 92
    }
  },
  Document {
    pageContent: 'حدثنا أبو اليمان... وبمحمد صلى الله عليه وسلم نبيا، فسكت.',
    metadata: {
      text_en: ' Narrated Anas bin Malik:... the Prophet became silent.',
      source: 'Sahih Bukhari',
      hadith_id: '93',
      chapter_no: '3',
      hadith_no: ' 93 ',
      chapter: 'Knowledge - كتاب العلم',
      line: 93
    }
  }
]
*/
```

Tested on my local machine:
Screenshot 2023-04-07 at 7 05 46 PM

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
this functionality seems great to me

**Comment by khairulhaaziq** [comment]
> this functionality seems great to me

thanks! next I am figuring out how to handle if the text is to large to be embedded, need to split the rows. I think this is a problem across all document loader/types. wonder if theres already a solution for this

**Comment by hwchase17** [comment]
> > this functionality seems great to me
> 
> thanks! next I am figuring out how to handle if the text is to large to be embedded, need to split the rows. I think this is a problem across all document loader/types. wonder if theres already a solution for this


so the pipeline is generally:

- load documents
- split documents (with the text splitters)
- embed text

so i think its more the responsibility of the text splitter to split documents if needed. does that make sense?

**Comment by khairulhaaziq** [comment]
> > > this functionality seems great to me
> > 
> > 
> > thanks! next I am figuring out how to handle if the text is to large to be embedded, need to split the rows. I think this is a problem across all document loader/types. wonder if theres already a solution for this
> 
> so the pipeline is generally:
> 
> * load documents
> * split documents (with the text splitters)
> * embed text
> 
> so i think its more the responsibility of the text splitter to split documents if needed. does that make sense?

sorry I am still going through the codebase and dont fully grasp it. do you mean  the current implementation should split the rows into multiple documents or that is the goal? by documents I mean the Document class, because i think you meant document in general sense. Also should I fix anything with my current code?

**Comment by khairulhaaziq** [comment]
I am trying to store a large csv using hsnwlib.fromDocuments, some texts are long, I am using the current CSVLoader for this, @hwchase17  is it correct that I should think of splitting the text into multiple rows:

```
Error: Request failed with status code 400
    at createError (/Users/a/dev/node/retrievalqa/node_modules/langchain/src/util/axios-fetch-adapter.js:363:17)
    at settle (/Users/a/dev/node/retrievalqa/node_modules/langchain/src/util/axios-fetch-adapter.js:34:7)
    at <anonymous> (/Users/a/dev/node/retrievalqa/node_modules/langchain/src/util/axios-fetch-adapter.js:212:11)
    at new Promise (<anonymous>)
    at fetchAdapter (/Users/a/dev/node/retrievalqa/node_modules/langchain/src/util/axios-fetch-adapter.js:205:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [AsyncFunction: fetchAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'OpenAI/NodeJS/3.2.1',
      Authorization: 'Bearer ****'
    },
    method: 'post',
    data: '{"model":"text-embedding-ada-002","input":[" Narrated Hudhaifa:                     The Prophet said to the people of Nijran, \\"I will send you the most trustworthy man.\\" (Every one of) the companions of the Prophet was looking forward (to be that person). He then sent Abu \'Ubaida."," Narrated Abu Bakra:                     I heard the Prophet talking at the pulpit while Al-Hasan was sitting beside him, and he (i.e. the Prophet ) was once looking at the people and at another time Al-Hasan, and saying, \\"This son of mine is a Saiyid (i.e. chief) and perhaps Allah will bring about an agreement between two sects of the Muslims through him.\\""," Narrated Usama bin Zaid:                     That the Prophet used to take him and Al-Hasan, and used to say, \\"O Allah! I love them, so please love them,\\" or said something similar."," Narrated Muhammad:                     Anas bin Malik said, \\"The head of Al-Husain was brought to \'Ubaidullah bin Ziyad and was put in a tray, and then Ibn Ziyad started playing with a stick at the nose and mouth of Al-Husain\'s head and saying something about his handsome features.\\" Anas then said (to him), \\"Al-Husain resembled the Prophet more than the others did.\\" Anas added, \\"His (i.e. Al-Husain\'s) hair was dyed with Wasma (i.e. a kind of plant used as a dye)."," Narrated Al-Bara:                     I saw the Prophet carrying Al-Hasan on his shoulder an saying, \\"O Allah! I love him, so please love him.\\""," Narrated `Uqba bin Al-Harith:                     I saw Abu Bakr carrying Al-Hasan and saying, \\"Let my father be sacrificed for you; you resemble the Prophet and not `Ali,\\" while `Ali was laughing at this."," Narrated Ibn `Umar:                     Abu Bakr used to say, \\"Please Muhammad (i.e. the Prophet) by doing good to his family.\\""," Narrated Anas:                     None resembled the Prophet more than Al-Hasan bin `Ali did."," Narrated Ibn Abi Nu\'m:                     A person asked `Abdullah bin `Umar whether a Muslim could kill flies. I heard him saying (in reply). \\"The people of Iraq are asking about the killing of flies while they themselves murdered the son of the daughter of Allah\'s Apostle . The Prophet said, They (i.e. Hasan and Husain) are my two sweet basils in this world.\\""," Narrated Jabir bin `Abdullah:                     `Umar used to say, \\"Abu Bakr is our chief, and he manumitted our chief,\\" meaning Bilal."," Narrated Qais:                     Bilal said to Abu Bakr, \\"If you have bought me for yourself then keep me (for yourself), but if you have bought me for Allah\'s Sake, then leave me for Allah\'s Work.\\""," Narrated Ibn `Abbas:                     Once the Prophet embraced me (pressed me to his chest) and said, \\"O Allah, teach him wisdom (i.e. the understanding of the knowledge of Qur\'an).","      Narrated \'Abdul Warith:                           The same but said, \\"O Allah, teach him (Ibn Abbas) the Book (i.e. the      understanding of the knowledge of Qur\'an).\\"Narrated Khalid:As above."," Narrated Anas:                     The Prophet had informed the people about the death of Zaid, Ja`far and Ibn Rawaha before the news of their death reached them. He said with his eyes flowing with tears, \\"Zaid took the flag and was martyred; then Ja`far took the flag and was martyred, and then Ibn Rawaha took the flag and was martyred. Finally the flag was taken by one of Allah\'s Swords (i.e. Khalid bin Al-Walid) and Allah gave them (i.e. the Muslims) victory.\\""," Narrated Masruq:                     `Abdullah (bin Mas`ud) was mentioned before `Abdullah bin `Amr. The latter said, \\"That is a man I continue to love because I heard Allah\'s Apostle saying, \' Learn the recitation of the Qur\'an from (any of these) four persons: `Abdullah bin Masud, Salim the freed slave of Abu Hudhaifa, Ubai bin Ka`b, and Mu`adh bin Jabal.\\" I do not remember whether he mentioned Ubai first or Mu`adh."," Narrated `Abdullah bin `Amr:                     Allah\'s Apostle neither talked in an insulting manner nor did he ever speak evil intentionally. He used to say, \\"The most beloved to me amongst you is the one who has the best character and manners.\\" He added, \\" Learn the Qur\'an from (any of these) four persons. `Abdullah bin Mas`ud, Salim the freed slave of Abu Hudhaifa, Ubai bin Ka`b, and Mu`adh bin Jabal.\\""," Narrated Alqama:                     I went to Sham and was offering a two-rak`at prayer; I said, \\"O Allah! Bless me with a (pious) companion.\\" Then I saw an old man coming towards me, and when he came near I said, (to myself), \\"I hope Allah has given me my request.\\" The man asked (me), \\"Where are you from?\\" I replied, \\"I am from the people of Kufa.\\" He said, \\"Weren\'t there amongst you the Carrier of the (Prophet\'s) shoes, Siwak and the ablution water container? Weren\'t there amongst you the man who was given Allah\'s Refuge from the Satan? And weren\'t there amongst you the man who used to keep the (Prophet\'s) secrets which nobody else knew? How did Ibn Um `Abd (i.e. `Abdullah bin Mas`ud) use to recite Surat-al-lail (the Night:92)?\\" I recited:-- \\"By the Night as it envelops By the Day as it appears in brightness. And by male and female.\\" (92.1- 3) On that, Abu Darda said, \\"By Allah, the Prophet made me read the Verse in this way after listening to him, but these people (of Sham) tried their best to let me say something different.\\""," Narrated `Abdur-Rahman bin Yazid:                     We asked Hudhaifa to tell us of a person resembling (to some extent) the Prophet in good appearance and straight forward behavior so that we may learn from him (good manners and acceptable conduct). Hudhaifa replied, \\"I do not know anybody resembling the Prophet (to some extent) in appearance and conduct more than Ibn Um `Abd."," Narrated Abu Musa Al-Ash`ari:                     My brother and I came from Yemen, and for some time we continued to consider `Abdullah bin Mas`ud as one of the members of the family of the Prophet because we used to see him and his mother going in the house of the Prophet very often."," Narrated Ibn Abu Mulaika:                     Muawiya offered one rak`a witr prayer after the `Isha prayer, and at that time a freed slave of Ibn `Abbas was present. He (i.e. the slave) went to Ibn `Abbas (and told him that Muawiya offered one rak`a witr prayer). Ibn `Abbas said, \\"Leave him, for he was in the company of Allah\'s Apostle.\\""," Narrated Ibn Abi Mulaika:                     Somebody said to Ibn `Abbas, \\"Can you speak to the chief of the believers Muwaiya, as he does not pray except one rak`a as witr?\\" Ibn `Abbas replied, \\"He is a Faqih (i.e. a learned man who can give religious verdicts) .\\""," Narrated Humran bin `Abbas:                     Muawiya said (to the people), \\"You offer a prayer which we, who were the companions of the Prophet never saw the Prophet offering, and he forbade its offering,\\" i.e. the two rak`at after the compulsory `Asr prayer."," Narrated Al-Miswar bin Makhrama:                     Allah\'s Apostle said, \\"Fatima is a part of me, and whoever makes her angry, makes me angry.\\""," Narrated Abu Salama:                     `Aisha said, \\"Once Allah\'s Apostle said (to me), \'O Aish (`Aisha)! This is Gabriel greeting you.\' I said, \'Peace and Allah\'s Mercy and Blessings be on him, you see what I don\'t see\' \\" She was addressing Allah \'s Apostle."," Narrated Abu Musa Al-Ash`ari:                     Allah\'s Apostle said, \\"Many amongst men attained perfection but amongst women none attained the perfection except Mary, the daughter of `Imran and Asiya, the wife of Pharaoh. And the superiority of `Aisha to other women is like the superiority of Tharid (i.e. an Arabic dish) to other meals.\\""," Narrated Anas bin Malik:                     Allah\'s Apostle said, \\"The superiority of `Aisha over other women is like the superiority of Tharid to other meals.\\""," Narrated Al-Qasim bin Muhammad:                     Once `Aisha became sick and Ibn `Abbas went to see her and said, \\"O mother of the believers! You are leaving for truthful fore-runners i.e. for Allah\'s Apostle and Abu Bakr."," Narrated Abu Wail:                     When `Ali sent `Ammar and Al-Hasan to (the people of) Kufa to urge them to fight, `Ammar addressed them saying, \\"I know that she (i.e. `Aisha) is the wife of the Prophet in this world and in the Hereafter (world to come), but Allah has put you to test, whether you will follow Him (i.e. Allah) or her.\\""," Narrated `Aisha:                     That she borrowed a necklace from Asma\' and it was lost. Allah\'s Apostle sent some of his companions to look for it. During their journey the time of prayer was due and they prayed without ablution. When they returned to the Prophet they complained about it. So the Divine Verse of Tayammum was revealed. Usaid bin Hudair said (to `Aisha), \\"May Allah reward you handsomely. By Allah, whenever you have a difficulty, Allah took you out of it and brought with it, a Blessing for the Muslims.\\""," Narrated Hisham\'s father:                     When Allah\'s Apostle was in his fatal illness, he started visiting his wives and saying, \\"Where will I be tomorrow?\\" He was anxious to be in `Aisha\'s home. `Aisha said, \\"So when it was my day, the Prophet became silent (no longer asked the question)."," Narrated Hisham\'s father:                     The people used to send presents to the Prophet on the day of `Aisha\'s turn. `Aisha said, \\"My companions (i.e. the other wives of the Prophet) gathered in the house of Um Salama and said, \\"0 Um Salama! By Allah, the people choose to send presents on the day of `Aisha\'s turn and we too, love the good (i.e. presents etc.) as `Aisha does. You should tell Allah\'s Apostle to tell the people to send their presents to him wherever he may be, or wherever his turn may be.\\" Um Salama said that to the Prophet and he turned away from her, and when the Prophet returned to her (i.e. Um Salama), she repeated the same, and the Prophet again turned awa'... 309858 more characters,
    url: 'https://api.openai.com/v1/embeddings'
  },
  request: Request {
    [Symbol(realm)]: { settingsObject: [Object] },
    [Symbol(state)]: {
      method: 'POST',
      localURLsOnly: false,
      unsafeRequest: false,
      body: [Object],
      client: [Object],
      reservedClient: null,
      replacesClientId: '',
      window: 'client',
      keepalive: false,
      serviceWorkers: 'all',
      initiator: '',
      destination: '',
      priority: null,
      origin: 'client',
      policyContainer: 'client',
      referrer: 'client',
      referrerPolicy: '',
      mode: 'cors',
      useCORSPreflightFlag: false,
      credentials: 'same-origin',
      useCredentials: false,
      cache: 'default',
      redirect: 'follow',
      integrity: '',
      cryptoGraphicsNonceMetadata: '',
      parserMetadata: '',
      reloadNavigation: false,
      historyNavigation: false,
      userActivation: false,
      taintedOrigin: false,
      redirectCount: 0,
      responseTainting: 'basic',
      preventNoCacheCacheControlHeaderModification: false,
      done: false,
      timingAllowFailed: false,
      headersList: [HeadersList],
      urlList: [Array],
      url: [URL]
    },
    [Symbol(signal)]: AbortSignal { aborted: false },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  },
  response: {
    ok: false,
    status: 400,
    statusText: 'Bad Request',
    headers: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    config: {
      transitional: [Object],
      adapter: [AsyncFunction: fetchAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',
      data: '{"model":"text-embedding-ada-002","input":[" Narrated Hudhaifa:                     The Prophet said to the people of Nijran, \\"I will send you the most trustworthy man.\\" (Every one of) the companions of the Prophet was looking forward (to be that person). He then sent Abu \'Ubaida."," Narrated Abu Bakra:                     I heard the Prophet talking at the pulpit while Al-Hasan was sitting beside him, and he (i.e. the Prophet ) was once looking at the people and at another time Al-Hasan, and saying, \\"This son of mine is a Saiyid (i.e. chief) and perhaps Allah will bring about an agreement between two sects of the Muslims through him.\\""," Narrated Usama bin Zaid:                     That the Prophet used to take him and Al-Hasan, and used to say, \\"O Allah! I love them, so please love them,\\" or said something similar."," Narrated Muhammad:                     Anas bin Malik said, \\"The head of Al-Husain was brought to \'Ubaidullah bin Ziyad and was put in a tray, and then Ibn Ziyad started playing with a stick at the nose and mouth of Al-Husain\'s head and saying something about his handsome features.\\" Anas then said (to him), \\"Al-Husain resembled the Prophet more than the others did.\\" Anas added, \\"His (i.e. Al-Husain\'s) hair was dyed with Wasma (i.e. a kind of plant used as a dye)."," Narrated Al-Bara:                     I saw the Prophet carrying Al-Hasan on his shoulder an saying, \\"O Allah! I love him, so please love him.\\""," Narrated `Uqba bin Al-Harith:                     I saw Abu Bakr carrying Al-Hasan and saying, \\"Let my father be sacrificed for you; you resemble the Prophet and not `Ali,\\" while `Ali was laughing at this."," Narrated Ibn `Umar:                     Abu Bakr used to say, \\"Please Muhammad (i.e. the Prophet) by doing good to his family.\\""," Narrated Anas:                     None resembled the Prophet more than Al-Hasan bin `Ali did."," Narrated Ibn Abi Nu\'m:                     A person asked `Abdullah bin `Umar whether a Muslim could kill flies. I heard him saying (in reply). \\"The people of Iraq are asking about the killing of flies while they themselves murdered the son of the daughter of Allah\'s Apostle . The Prophet said, They (i.e. Hasan and Husain) are my two sweet basils in this world.\\""," Narrated Jabir bin `Abdullah:                     `Umar used to say, \\"Abu Bakr is our chief, and he manumitted our chief,\\" meaning Bilal."," Narrated Qais:                     Bilal said to Abu Bakr, \\"If you have bought me for yourself then keep me (for yourself), but if you have bought me for Allah\'s Sake, then leave me for Allah\'s Work.\\""," Narrated Ibn `Abbas:                     Once the Prophet embraced me (pressed me to his chest) and said, \\"O Allah, teach him wisdom (i.e. the understanding of the knowledge of Qur\'an).","      Narrated \'Abdul Warith:                           The same but said, \\"O Allah, teach him (Ibn Abbas) the Book (i.e. the      understanding of the knowledge of Qur\'an).\\"Narrated Khalid:As above."," Narrated Anas:                     The Prophet had informed the people about the death of Zaid, Ja`far and Ibn Rawaha before the news of their death reached them. He said with his eyes flowing with tears, \\"Zaid took the flag and was martyred; then Ja`far took the flag and was martyred, and then Ibn Rawaha took the flag and was martyred. Finally the flag was taken by one of Allah\'s Swords (i.e. Khalid bin Al-Walid) and Allah gave them (i.e. the Muslims) victory.\\""," Narrated Masruq:                     `Abdullah (bin Mas`ud) was mentioned before `Abdullah bin `Amr. The latter said, \\"That is a man I continue to love because I heard Allah\'s Apostle saying, \' Learn the recitation of the Qur\'an from (any of these) four persons: `Abdullah bin Masud, Salim the freed slave of Abu Hudhaifa, Ubai bin Ka`b, and Mu`adh bin Jabal.\\" I do not remember whether he mentioned Ubai first or Mu`adh."," Narrated `Abdullah bin `Amr:                     Allah\'s Apostle neither talked in an insulting manner nor did he ever speak evil intentionally. He used to say, \\"The most beloved to me amongst you is the one who has the best character and manners.\\" He added, \\" Learn the Qur\'an from (any of these) four persons. `Abdullah bin Mas`ud, Salim the freed slave of Abu Hudhaifa, Ubai bin Ka`b, and Mu`adh bin Jabal.\\""," Narrated Alqama:                     I went to Sham and was offering a two-rak`at prayer; I said, \\"O Allah! Bless me with a (pious) companion.\\" Then I saw an old man coming towards me, and when he came near I said, (to myself), \\"I hope Allah has given me my request.\\" The man asked (me), \\"Where are you from?\\" I replied, \\"I am from the people of Kufa.\\" He said, \\"Weren\'t there amongst you the Carrier of the (Prophet\'s) shoes, Siwak and the ablution water container? Weren\'t there amongst you the man who was given Allah\'s Refuge from the Satan? And weren\'t there amongst you the man who used to keep the (Prophet\'s) secrets which nobody else knew? How did Ibn Um `Abd (i.e. `Abdullah bin Mas`ud) use to recite Surat-al-lail (the Night:92)?\\" I recited:-- \\"By the Night as it envelops By the Day as it appears in brightness. And by male and female.\\" (92.1- 3) On that, Abu Darda said, \\"By Allah, the Prophet made me read the Verse in this way after listening to him, but these people (of Sham) tried their best to let me say something different.\\""," Narrated `Abdur-Rahman bin Yazid:                     We asked Hudhaifa to tell us of a person resembling (to some extent) the Prophet in good appearance and straight forward behavior so that we may learn from him (good manners and acceptable conduct). Hudhaifa replied, \\"I do not know anybody resembling the Prophet (to some extent) in appearance and conduct more than Ibn Um `Abd."," Narrated Abu Musa Al-Ash`ari:                     My brother and I came from Yemen, and for some time we continued to consider `Abdullah bin Mas`ud as one of the members of the family of the Prophet because we used to see him and his mother going in the house of the Prophet very often."," Narrated Ibn Abu Mulaika:                     Muawiya offered one rak`a witr prayer after the `Isha prayer, and at that time a freed slave of Ibn `Abbas was present. He (i.e. the slave) went to Ibn `Abbas (and told him that Muawiya offered one rak`a witr prayer). Ibn `Abbas said, \\"Leave him, for he was in the company of Allah\'s Apostle.\\""," Narrated Ibn Abi Mulaika:                     Somebody said to Ibn `Abbas, \\"Can you speak to the chief of the believers Muwaiya, as he does not pray except one rak`a as witr?\\" Ibn `Abbas replied, \\"He is a Faqih (i.e. a learned man who can give religious verdicts) .\\""," Narrated Humran bin `Abbas:                     Muawiya said (to the people), \\"You offer a prayer which we, who were the companions of the Prophet never saw the Prophet offering, and he forbade its offering,\\" i.e. the two rak`at after the compulsory `Asr prayer."," Narrated Al-Miswar bin Makhrama:                     Allah\'s Apostle said, \\"Fatima is a part of me, and whoever makes her angry, makes me angry.\\""," Narrated Abu Salama:                     `Aisha said, \\"Once Allah\'s Apostle said (to me), \'O Aish (`Aisha)! This is Gabriel greeting you.\' I said, \'Peace and Allah\'s Mercy and Blessings be on him, you see what I don\'t see\' \\" She was addressing Allah \'s Apostle."," Narrated Abu Musa Al-Ash`ari:                     Allah\'s Apostle said, \\"Many amongst men attained perfection but amongst women none attained the perfection except Mary, the daughter of `Imran and Asiya, the wife of Pharaoh. And the superiority of `Aisha to other women is like the superiority of Tharid (i.e. an Arabic dish) to other meals.\\""," Narrated Anas bin Malik:                     Allah\'s Apostle said, \\"The superiority of `Aisha over other women is like the superiority of Tharid to other meals.\\""," Narrated Al-Qasim bin Muhammad:                     Once `Aisha became sick and Ibn `Abbas went to see her and said, \\"O mother of the believers! You are leaving for truthful fore-runners i.e. for Allah\'s Apostle and Abu Bakr."," Narrated Abu Wail:                     When `Ali sent `Ammar and Al-Hasan to (the people of) Kufa to urge them to fight, `Ammar addressed them saying, \\"I know that she (i.e. `Aisha) is the wife of the Prophet in this world and in the Hereafter (world to come), but Allah has put you to test, whether you will follow Him (i.e. Allah) or her.\\""," Narrated `Aisha:                     That she borrowed a necklace from Asma\' and it was lost. Allah\'s Apostle sent some of his companions to look for it. During their journey the time of prayer was due and they prayed without ablution. When they returned to the Prophet they complained about it. So the Divine Verse of Tayammum was revealed. Usaid bin Hudair said (to `Aisha), \\"May Allah reward you handsomely. By Allah, whenever you have a difficulty, Allah took you out of it and brought with it, a Blessing for the Muslims.\\""," Narrated Hisham\'s father:                     When Allah\'s Apostle was in his fatal illness, he started visiting his wives and saying, \\"Where will I be tomorrow?\\" He was anxious to be in `Aisha\'s home. `Aisha said, \\"So when it was my day, the Prophet became silent (no longer asked the question)."," Narrated Hisham\'s father:                     The people used to send presents to the Prophet on the day of `Aisha\'s turn. `Aisha said, \\"My companions (i.e. the other wives of the Prophet) gathered in the house of Um Salama and said, \\"0 Um Salama! By Allah, the people choose to send presents on the day of `Aisha\'s turn and we too, love the good (i.e. presents etc.) as `Aisha does. You should tell Allah\'s Apostle to tell the people to send their presents to him wherever he may be, or wherever his turn may be.\\" Um Salama said that to the Prophet and he turned away from her, and when the Prophet returned to her (i.e. Um Salama), she repeated the same, and the Prophet again turned awa'... 309858 more characters,
      url: 'https://api.openai.com/v1/embeddings'
    },
    request: Request {
      [Symbol(realm)]: [Object],
      [Symbol(state)]: [Object],
      [Symbol(signal)]: [AbortSignal],
      [Symbol(headers)]: [HeadersList]
    },
    data: { error: [Object] }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**Comment by khairulhaaziq** [comment]
> > > this functionality seems great to me
> > 
> > 
> > thanks! next I am figuring out how to handle if the text is to large to be embedded, need to split the rows. I think this is a problem across all document loader/types. wonder if theres already a solution for this
> 
> so the pipeline is generally:
> 
> * load documents
> * split documents (with the text splitters)
> * embed text
> 
> so i think its more the responsibility of the text splitter to split documents if needed. does that make sense?

I got it now. instead of using loader.load(), I should use loader.loadAndSplit(). so now it works perfect.

**Comment by khairulhaaziq** [comment]
> I got it now. instead of using loader.load(), I should use loader.loadAndSplit(). so now it works perfect.

for csv in particular. should we add a metadata signifying a row has been splitted, putting chunk number, e.g. if a row splitted into 3, theres a metadata of chunk: 1/3 , chunk: 2/3 and chunk 3/3 ?

also currently theres no option to modify the loadAndSplit function to customize chunkSize and chunkOverlap. should I override the loadAndSplit function in the CSVLoader class?

**Comment by khairulhaaziq** [comment]
@nfcampos I would like a review, used for my use cases and worked for me! If you approve I will try to find a way to add the same feature for python and other document loaders!

**Review by nfcampos — COMMENTED** [review]
One comment, I'll address

**Comment by bracesproul** [comment]
@k11q going to close due to merge conflicts. If you'd still like to get this merged in, please open off of an up-to-date main branch, and I'll review. Thank you!

**Pull request closed without merging**
