### PR TITLE
community[patch], azure-openai[patch]: tag langchainjs in azure integrations calls

### PR DESCRIPTION
**Pull request by sinedied**
Adds `langchainjs*` in the user agent or logs, so LangChain.js usage is reported in Azure OpenAI

### CODE REVIEW

**Comment by jacoblee93** [comment]
Thank you!

**Comment by jacoblee93** [comment]
Could you run `yarn format`?

**Comment by sinedied** [comment]
Fixed, my bad!

**Comment by jacoblee93** [comment]
Thank you!

**Comment by jacoblee93** [comment]
Live in #4437

**Pull request merged**
