### PR TITLE
community[patch]: Allow a raw filter option for Redis Vector Store

### LINKED ISSUE #4559: Redis Vector Store Should Support Custom Filter Queries
Currently the filter for Redis Vector Store is a simple "does the meta data contain any of these strings" check.  While a more robust system would be nice, even a simple "raw" option would work such that clients can use and combination of AND, OR, etc. for filtering.

### PR DESCRIPTION
**Pull request by EricThompson-PeopleReign**
- Update existing filter test to make sure the `join` is exercised.
- Add raw filter (pass string instead of array) option

Fixes #4559

### CODE REVIEW

**Comment by jacoblee93** [comment]
Looks reasonable, thank you!

**Comment by jacoblee93** [comment]
Seems unit test is failing?

**Comment by EricThompson-PeopleReign** [comment]
> Seems unit test is failing?

Oops!  Typo in the adjustment of the `prepareFilter` code.  I have corrected it and pushed.

**Comment by EricThompson-PeopleReign** [comment]
@jacoblee93 could you have another look?

**Pull request merged**
