### PR TITLE
Error: No tools_call in message in langgraph with anthropic

### PR DESCRIPTION
**Pull request by scenaristeur**
fix https://github.com/langchain-ai/langgraphjs/issues/206#issuecomment-2504595375

Fixes https://github.com/langchain-ai/langgraphjs/issues/206

### CODE REVIEW

**Comment by scenaristeur** [comment]
oups i forgot the signature  

`async parseResult(generations: ChatGeneration[]): Promise<ParsedToolCall[]> {`

**Review by bracesproul — COMMENTED** [review]
@scenaristeur this looks reasonable, but before I approve could you send me some code I can run which will trigger the error that this PR fixes? Thank you!

**Comment by scenaristeur** [comment]
> @scenaristeur this looks reasonable, but before I approve could you send me some code I can run which will trigger the error that this PR fixes? Thank you!

Superviser tuto
https://github.com/langchain-ai/langgraphjs/issues/206

**Comment by bracesproul** [comment]
> > @scenaristeur this looks reasonable, but before I approve could you send me some code I can run which will trigger the error that this PR fixes? Thank you!
> 
> Superviser tuto [langchain-ai/langgraphjs#206](https://github.com/langchain-ai/langgraphjs/issues/206)

The issue in that notebook is unrelated to the `ChatAnthropic` class. Checkout my comment [here](https://github.com/langchain-ai/langgraphjs/issues/206#issuecomment-2529902371). I'm going to close this PR for now, but if you still get this error, please send me a code snippet I can use to reproduce it (without deprecated code) and we can go from there. Thank you

**Pull request closed without merging**
