### PR TITLE
docs[minor]: Replace deprecated code examples with LCEL & AgentExecutor

### PR DESCRIPTION
**Pull request by Srijan-D**
Description: Added LangChain v0.2 support For the LangChain AgentExecutor using react agent executor which manages a state that is defined by a list of messages in a similar way to the AgentExecutor.  Removed classes as well like LLMChain which were deprecated from LangChain v0.1.

Used the LangChain Expression Language (LCEL) instead of LLMChain deprecated class

### CODE REVIEW

**Review by bracesproul — APPROVED** [review]
nice! Thanks for doing this

**Review by bracesproul — COMMENTED** [review]
hey looks like the format CI check is failing, could you run `yarn format` inside `./examples` and push up those changes files

**Comment by Srijan-D** [comment]
Sure let me check :)

**Comment by Srijan-D** [comment]
Done I have pushed it.

**Pull request merged**
