### PR TITLE
community[patch]: Astra updates

### PR DESCRIPTION
**Pull request by mfortman11**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=etsTvLY)

Utilizes new astra client features

Add Docs now updates docs w/ the same ids

### CODE REVIEW

**Comment by jacoblee93** [comment]
Looks good! Can you mark `batchSize` as deprecated to let them know that it no longer has an effect?

**Comment by mfortman11** [comment]
All set

**Review by bracesproul — APPROVED** [review]
tyvm!

**Review by bracesproul — COMMENTED** [review]
looks like CI is failing, could you fix and re-request my review so I can merge?

**Comment by mfortman11** [comment]
@bracesproul sorry for the delay the the issue appears to be around `batchSize` with this change it is no longer need so i added the deprecated note to it per Jacobs request but that is the cause of the build error

```  /** @deprecated astra-db-ts > 1.0.0 handles this */
  private readonly batchSize: number; ```
  
  Lmk how i should handle this

**Review by bracesproul — APPROVED** [review]
I just pushed a commit doing two things:
1. dropped the `batchSize` class property. Since it was already marked as `private readonly` deleting it won't be breaking for anyone.
2. I added a `console.warn` notifying users that passing in the `batchSize` arg has no effect anymore.

Thanks for doing this! Going to get it merged asap

**Pull request merged**
