### PR TITLE
community[patch]: Fix strict mode comparison and formatting for llm graph transformer

### PR DESCRIPTION
**Pull request by tomasonjo**
@easwee

### CODE REVIEW

**Comment by tomasonjo** [comment]
Also removed serialization of the document for graph document

**Comment by easwee** [comment]
Looks ok.

**Comment by jacoblee93** [comment]
Thank you!

**Comment by jacoblee93** [comment]
Could you please run `yarn format`

**Comment by tomasonjo** [comment]
Done

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
