### PR TITLE
community[patch]: support all opensearch term level query type in filter #4121

### LINKED ISSUE #4121: [Feature request] support "range" filter in opensearch with similaritySearchWithScore
support "range" filter in opensearch with similaritySearchWithScore

Opensearch have range filter that can be used as per below:

```
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "metadata.field1": "value1"
          }
        },
        {
          "range": {
            "metadata.date": {
              "gte": "2024-03-01 10:00:00.000000",
              "lte": "2024-03-31 10:00:00.000000"
            }
          }
        }
      ]
    }
  }
```

In `similaritySearchWithScore`, it seems filter passed the values directly into "term". It should have more flexibility to construct filter array so other type of filter like range can be used.

image

### PR DESCRIPTION
**Pull request by fuleinist**
support all opensearch term level query type in filter 

Fixes #4121

### CODE REVIEW

**Comment by jacoblee93** [comment]
Looks solid, thank yoU!

**Comment by jacoblee93** [comment]
Am getting some CI failures:
```
Error: @langchain/community:build: src/vectorstores/opensearch.ts(314,22): error TS7006: Parameter 'filter' implicitly has an 'any' type.
Error: @langchain/community:build: src/vectorstores/opensearch.ts(321,25): error TS18047: 'value' is possibly 'null'.
Error: @langchain/community:build: src/vectorstores/opensearch.ts(327,31): error TS18047: 'value' is possibly 'null'.
Error: @langchain/community:build: src/vectorstores/opensearch.ts(329,29): error TS18047: 'value' is possibly 'null'.
Error: @langchain/community:build: src/vectorstores/opensearch.ts(331,32): error TS18047: 'value' is possibly 'null'.
Error: @langchain/community:build: src/vectorstores/opensearch.ts(334,20): error TS18047: 'value' is possibly 'null'.
Error: @langchain/community:build: src/vectorstores/opensearch.ts(335,19): error TS18047: 'value' is possibly 'null'.
Error: @langchain/community:build: src/vectorstores/opensearch.ts(336,20): error TS18047: 'value' is possibly 'null'.
Error: @langchain/community:build: src/vectorstores/opensearch.ts(337,19): error TS18047: 'value' is possibly 'null'.
Error: @langchain/community:build: src/vectorstores/opensearch.ts(340,32): error TS18047: 'value' is possibly 'null'.
Error: @langchain/community:build: src/vectorstores/opensearch.ts(342,35): error TS18047: 'value' is possibly 'null'.
Error: @langchain/community:build: src/vectorstores/opensearch.ts(344,34): error TS18047: 'value' is possibly 'null'.
```

Do you think you could have a look?

**Comment by fuleinist** [comment]
> Do you think you could have a look?

[Resolved ](https://github.com/langchain-ai/langchainjs/pull/4157/commits/9308272168c271b35f94ca7d8ea18bb6468f4531)👍

**Comment by jacoblee93** [comment]
It's not happy - can you run `yarn lint`?

**Comment by fuleinist** [comment]
> It's not happy - can you run `yarn lint`?

same as my other PR, local lint and format check all passed...

**Comment by jacoblee93** [comment]
```
Error: @langchain/community:build: src/vectorstores/tests/opensearch.int.test.ts(40,5): error TS2322: Type 'number' is not assignable to type 'string | string[] | FilterTypeValue | null'.
```

On `yarn test`

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
