### PR TITLE
DRAFT: Add Graph store and Graph QA

### LINKED ISSUE #2383: [Question] Graph DB QA chain for JS
I don't seem to be able to find the Graph DB QA chain in the ts version of the library. Is it Python only?

### PR DESCRIPTION
**Pull request by gkorland**
An initial PR just to see that I'm building the right API.
Fixes #2383

### CODE REVIEW

**Comment by jacoblee93** [comment]
Will have a look at this tomorrow! Apologies for the delay.

**Comment by gkorland** [comment]
@jacoblee93 no worries, I really didn't do too much, just did a very early PR to get your feedback and make sure I'm going in the right direction before I put more time.

**Comment by jacoblee93** [comment]
Hey @gkorland, had a chat with @baskaryan and I don't think we have a clear idea of the right common interface between graph stores at the moment - would you be up for implementing it like you did in Python or extending a very minimal base class?

I think adding some `asRetriever()` wrapper can make Falkor and other GraphDBs interact usefully with other LangChain constructs.

**Comment by gkorland** [comment]
I pushed the other day a simple interface for GraphStore see: https://github.com/langchain-ai/langchain/pull/11012 
https://github.com/langchain-ai/langchain/blob/f30a8465fb41788de109ea3a0a02cd855ec38d5f/libs/langchain/langchain/graphs/graph_store.py

**Comment by gkorland** [comment]
@jacoblee93 I noticed the PRs https://github.com/langchain-ai/langchainjs/pull/2741 https://github.com/langchain-ai/langchainjs/pull/2749 were merged so I guess there is no need for this PR, I'll submit a new PR based on these PRs

**Comment by gkorland** [comment]
@jacoblee93 see https://github.com/langchain-ai/langchainjs/pull/2774

**Pull request closed without merging**
