### PR TITLE
[draft] Add Diskann index for Azure CosmosDB

### PR DESCRIPTION
**Pull request by crisjy**
Fixes # (issue)

### CODE REVIEW

**Review by jacoblee93 — APPROVED** [review]
Thank you! Is this ready to go?

**Comment by crisjy** [comment]
have a new pr for diskann and test successfully, this pr with be abandoned, thanks a lot!

**Comment by crisjy** [comment]
https://github.com/langchain-ai/langchainjs/pull/7225

**Comment by crisjy** [comment]
have a new pr for this https://github.com/langchain-ai/langchainjs/pull/7225

**Pull request closed without merging**
