### PR TITLE
community[patch]: fix astra initialize error

### PR DESCRIPTION
**Pull request by nicoloboschi**
Currently in the `AstraDBVectorStore#initialize` method if there is an error while creating the collection, the error is suppressed, assuming the collection already exists. This is wrong because:
- if the collection already exists with the same options, the Astra Data API won't return errors
- In case of auth, network or server errors, the user can't really see the errors and no error is raised

### CODE REVIEW

**Comment by jacoblee93** [comment]
Thank you!

**Comment by Gr33nLight** [comment]
Hello regarding this, I noticed a pretty big impact of the call ` this.astraDBClient.createCollection ` in the ` initialize `  in terms of response time.  Even if the collection already exists, this call takes multiple seconds to complete (2.2 to 2.5s im my testing). This is not ideal if the collection is already present, may a suggest in a pull request the option to disable automatic collection creation?

@nicoloboschi  @jacoblee93

**Comment by nicoloboschi** [comment]
@Gr33nLight I don't think it's related to the pull itself. the API calls are the same.
Checking if the collection already exists would take the same time.
Skipping the collection creation is very risky from a usability point of view 🤔

**Comment by Gr33nLight** [comment]
Yes I agree in regards to the usability, It is more of a specific case, in our product speed is a priority and having 2s added to every request is not the best. We are using a modified version so its not that big of a issue for us, but I wanted to point this out anyways as I was not experiencing this slow down with the other adapters. 
Maybe I'll check with the guys at Datastax to see if something can be done at client level, to maybe speed up some calls.

**Pull request merged**
