### PR TITLE
community[minor]: accept num_predict option as a param

### LINKED ISSUE #3925: improvement: add maxTokens property for ChatOllama
```maxTokens``` property is missing for Ollama Chat model

### PR DESCRIPTION
**Pull request by ashokgelal**
Fixes #3925

### CODE REVIEW

**Review by bracesproul — APPROVED** [review]
Thanks for adding this! I pushed up one small commit adding a test, but this should be able to merge once CI passes!

**Comment by ashokgelal** [comment]
@bracesproul Thanks for the test and a super quick merge. What's the timeline for the next release with this fix? How often is the release?

**Comment by bracesproul** [comment]
@ashokgelal typically once every 1-5 days. Really depends on how many things are in the queue to be released. The last release was 3 days ago so you should expect a release within a couple days I'd say.

**Comment by ashokgelal** [comment]
@bracesproul Sorry for bring this up - I see the latest version being released but installing the latest version doesn't seem to be using the latest code. One interesting thing I've noticed that on npm the download stats for anything higher 0.0.214 is all 0. Some bug with release process? https://www.npmjs.com/package/langchain/v/0.1.2?activeTab=versions

**Comment by bracesproul** [comment]
> @bracesproul Sorry for bring this up - I see the latest version being released but installing the latest version doesn't seem to be using the latest code. One interesting thing I've noticed that on npm the download stats for anything higher 0.0.214 is all 0. Some bug with release process? https://www.npmjs.com/package/langchain/v/0.1.2?activeTab=versions

These code changes are inside the `@langchain/community` package, so you should be installing that to access it instead of through `langchain`. Going through the `langchain` package will be deprecated in `0.2`. Also, I just installed `langchain` and `@langchain/community` on a fresh project and was able to find the most recent version with your changes. Have you tried deleting the `node_modules` folder and re-installing?

**Comment by ashokgelal** [comment]
Ok, that fixed it. Thanks.

**Pull request merged**
