### PR TITLE
Update aws.mdx

### PR DESCRIPTION
**Pull request by jasel-lewis**
For the demonstrated import of `DynamoDBChatMessageHistory`, updated the package to the newer `@langchain/community` package (`@langchain/community/stores/message/dynamodb`).

### CODE REVIEW

**Review by bracesproul — COMMENTED** [review]
Thanks for adding this! I noticed there are a few more instances of `langchain` imports in this file when they should be from`@langchain/community`, would you have time to push those up too? If not I can handle!

**Comment by jasel-lewis** [comment]
Brace -

You're most welcome and I'd love to help.

Just a note: we're under intense pressure to get a production release (of
what we're doing) out by the end of this month. This fix was just something
that annoyed me (no offense intended) and was quick and easy to get done.

I'll circle back on your request as soon as I can, but feel free to jump in
if you can't wait on me.

Thank you,
R. J.

**Comment by jacoblee93** [comment]
Thank you!

**Comment by jacoblee93** [comment]
We will handle the rest of those missed imports.

**Pull request merged**
