### PR TITLE
Add OpenAICreateImage Tool

### PR DESCRIPTION
**Pull request by Marviel**
Adds the OpenAI CreateImage tool, so you can ask your agents for images :)

Hopefully self-documenting. Open to feedback!

### CODE REVIEW

**Comment by Marviel** [comment]
Hey @nfcampos I'm not sure why my build is failing here but I'm happy to fix if there's something I can do.

**Comment by nfcampos** [comment]
@Marviel Thanks for this! You can fix the CI by running `yarn format` in `langchain` folder

**Comment by Marviel** [comment]
> @Marviel Thanks for this! You can fix the CI by running `yarn format` in `langchain` folder

that did it, thanks :)

**Review by hwchase17 — APPROVED** [review]
this looks great to me, but lets hold off for a tiny bit longer! we have a corresponding pr in the python packages that would be good to land at the same time

**Pull request closed without merging**
