### PR TITLE
community[patch]: fix: Zhipu api key expired after 3 minutes

### LINKED ISSUE #5037: ZhipuAIEmbeddings  bug
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import { ZhipuAIEmbeddings } from "@langchain/community/embeddings/zhipuai";

const model = new ZhipuAIEmbeddings({});
const res = await model.embedQuery(
  "What would be a good company name a company that makes colorful socks?"
);
console.log({ res });

### Error Message and Stack Trace (if applicable)

 throw new Error(`Error getting embeddings from ZhipuAI. ${JSON.stringify(await fetchResponse.json(), null, 2)}`); ^ Error: Error getting embeddings from ZhipuAI. { "error": { "code": "1000", "message": "身份验证失败。" } } 

### Description

 throw new Error(`Error getting embeddings from ZhipuAI. ${JSON.stringify(await fetchResponse.json(), null, 2)}`); ^ Error: Error getting embeddings from ZhipuAI. { "error": { "code": "1000", "message": "身份验证失败。" } } 

### System Info

    "@langchain/community": "^0.0.41",
    "@langchain/core": "^0.1.49",
    "langchain": "^0.1.28",

### PR DESCRIPTION
**Pull request by jeasonnow**
Fixes #5037

### CODE REVIEW

**Comment by jacoblee93** [comment]
Thanks! Could you make sure you run `yarn format`?

**Comment by jacoblee93** [comment]
Getting:
```
@langchain/community:build: src/embeddings/zhipuai.ts(62,5): error TS2322: Type 'string | undefined' is not assignable to type 'string'.
```

Can you have a look?

**Comment by jeasonnow** [comment]
> Getting:
> 
> ```
> @langchain/community:build: src/embeddings/zhipuai.ts(62,5): error TS2322: Type 'string | undefined' is not assignable to type 'string'.
> ```
> 
> Can you have a look?

Okay, I’ll fix it right away.

**Comment by jeasonnow** [comment]
> Thanks! Could you make sure you run `yarn format`?

Yes, I executed the format.

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
