### PR TITLE
fix: wrong error handling in baidu wenxin chat model (#3115)

### LINKED ISSUE #3115: ChatBaiduWenxin No response
Whether it is the direct use of the model or the chain, it is a direct response and fast. Generally speaking, it should not respond so quickly, and no error has been detected.

IMG-2023-11-01-16 43 30@2x
IMG-2023-11-01-16 43 45@2x

```ts
export type HubChatBaiduWenxinInput = Partial<BaiduWenxinChatInput> & BaseChatModelParams;

export class HubChatBaiduWenxin extends ChatBaiduWenxin {
  constructor(fields: HubChatBaiduWenxinInput) {
    super({
      baiduApiKey: BAIDU_API_KEY,
      baiduSecretKey: BAIDU_SECRET_KEY,
      temperature: 0.1,
      ...fields,
    });
  }
}
 const model = new HubChatBaiduWenxin({
      modelName: WenXinModel['ERNIE-Bot-4'],
      temperature: 0,
      callbacks: [
        {
          handleChainError(err) {
            console.log(err);
          },
          handleRetrieverError(err) {
            console.log(err, '======');
          },
        },
      ],
    });

    const messages = [new HumanMessage('Hello')];
    const res = await model.call(messages);
    console.log(res, '----->-----');
    const vectorStore = this.createVectorStore('knowledge');
    const relevantDocs = await vectorStore.similaritySearch(question);

    const chain = createLLMChain(QA_TEMPLATE, model);

    await chain
      .call(
        {
          context: relevantDocs.map((item) => item.pageContent).join('\n\n'),
          question,
          chatHistory: '',
        },
        [new ConsoleCallbackHandler()],
      )
      .then((res) => {
        console.log(res, '===========');
      })
      .catch((e) => {
        console.log(e, '-----');
      });
```

### PR DESCRIPTION
**Pull request by PeterPanZH**
Fix wrong error handling in baidu wenxin chat model (#3115)

### CODE REVIEW

**Comment by jacoblee93** [comment]
LGTM, thank you! @sunner are you able to have a final look?

**Comment by sunner** [comment]
Hi @PeterPanZH , could you add tests which can trigger error? The test file is `langchain/src/chat_models/tests/chatbaiduwenxin.int.test.ts`. Run it with `yarn test:single langchain/src/chat_models/tests/chatbaiduwenxin.int.tes.ts`

**Comment by sunner** [comment]
@jacoblee93 I reviewed the code and ran the tests. Everything looks good. A merge will be ok.

PS. @PeterPanZH comes from the Baidu ERNIE team.

**Comment by jacoblee93** [comment]
Thank you both 🙏

**Pull request merged**
