### PR TITLE
deps: update @anthropic-ai/sdk to 0.27.3 from 0.25.2

### LINKED ISSUE #6662: Uncaught AnthropicError: running in a browser-like environment
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
import { ChatAnthropic } from "@langchain/anthropic";
import { ChatPromptTemplate } from "@langchain/core/prompts";
import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";

console.log("Anthropic API Key is:", import.meta.env.VITE_ANTHROPIC_API_KEY);

const calculatorSchema = z.object({
  operation: z
    .enum(["add", "subtract", "multiply", "divide", "average"])
    .describe("The type of operation to execute."),
  numbers: z.array(z.number()).describe("The numbers to operate on."),
});

const weatherSchema = z
  .object({
    location: z.string().describe("The name of city to get the weather for."),
  })
  .describe(
    "Get the weather of a specific location and return the temperature in Celsius."
  );

const tools = [
  {
    name: "calculator",
    description: "A simple calculator tool.",
    input_schema: zodToJsonSchema(calculatorSchema),
  },
  {
    name: "get_weather",
    description: "Get the weather of a location",
    input_schema: zodToJsonSchema(weatherSchema),
  },
];

const model = new ChatAnthropic({
  apiKey: import.meta.env.VITE_ANTHROPIC_API_KEY,
  model: "claude-3-opus-20240229",
}).bind({
  tools,
});

const prompt = ChatPromptTemplate.fromMessages([
  [
    "system",
    "You are a helpful assistant who always uses tools to ensure you provide accurate, up to date information.",
  ],
  ["human", "{input}"],
]);

// Chain your prompt and model together
const chain = prompt.pipe(model);

const response = await chain.invoke({
  input:
    "What is the current weather in new york, and san francisco? Also, what is the average of these numbers: 2273,7192,272,92737?",
});

console.log(JSON.stringify(response, null, 2));
const App: React.FC = () => {
  return (
    <>
      <h1>Anthropic API</h1>
      <div>App Component {JSON.stringify(response, null, 2)}</div>
    </>
  );
};

export default App;
```

### Error Message and Stack Trace (if applicable)

```
chunk-QMHROIDE.js?v=6aec3b6c:2214 Uncaught AnthropicError: It looks like you're running in a browser-like environment, which is disabled to protect your secret API credentials from attackers. If you have a strong business need for client-side use of this API, please open a GitHub issue with your use-case and security mitigations.
    at new Anthropic (chunk-QMHROIDE.js?v=6aec3b6c:2214:13)
    at ChatAnthropic.completionWithRetry (chunk-QMHROIDE.js?v=6aec3b6c:5709:26)
    at ChatAnthropic._generateNonStreaming (chunk-QMHROIDE.js?v=6aec3b6c:5634:33)
    at ChatAnthropic._generate (chunk-QMHROIDE.js?v=6aec3b6c:5672:19)
    at chunk-QMHROIDE.js?v=6aec3b6c:3167:90
    at Array.map (<anonymous>)
    at ChatAnthropic._generateUncached (chunk-QMHROIDE.js?v=6aec3b6c:3167:61)
    at async ChatAnthropic.invoke (chunk-QMHROIDE.js?v=6aec3b6c:3056:20)
    at async _RunnableSequence.invoke (chunk-MNCD2AJQ.js?v=6aec3b6c:12814:21)
    at async App.tsx:54:18
```

### Description

I am following a simple example as shown above. I have configured the API key in the `vite` config. When I run the program, the API key is displayed in the console. However, I'm getting an error when trying to make a request to the Anthropic endpoint. OpenAI's requests are functioning well.

Recently, Anthropic implemented CORS feature as mentioned [here](https://github.com/anthropics/anthropic-sdk-typescript/issues/248). So, is this error potentially due to the missing property in the interface? Please clarify.

### System Info

macOS mini Apple M2 14.6.1 (23G93)
node v22.7.0
langchain@0.2.17

### PR DESCRIPTION
**Pull request by rootCircle**
This PR updates the version of [@anthropic-ai/sdk](https://www.npmjs.com/package/@anthropic-ai/sdk) from 0.25.2 to 0.27.3 to allow introduction of `dangerouslyAllowBrowser` flag in langchain as well!

Updates in upstream also include streaming helpers, introduced beta prompt caching and further streaming capabilities. 

### Purpose

[anthropic-sdk-typescript](https://github.com/anthropics/anthropic-sdk-typescript) has recently introduced support for browser from their SDK as well in v0.27.0 ([pr here](https://github.com/anthropics/anthropic-sdk-typescript/pull/504)). But, this is still not in langchain yet!

> Anthropic had been resistant to adding this feature because it can encourage a nasty anti-pattern: if you embed your API key in your client code, anyone with access to that site can steal your API key and use it to make requests on your behalf.
> 
> Despite that, there are legitimate use cases for this feature. It’s fine for internal tools exposed to trusted users, or you can implement a “bring your own API key” pattern where users supply their own key to use with your client-side app.

What it means is we can now make a call to Anthropic via Browser as well, through `dangerouslyAllowBrowser` flag present in `ClientOptions`! Also, we won't require to add that flag on our side as well, because we're importing the ClientOptions from anthropic-sdk only, instead of having our own implementation!

Hence, the invocation becomes like this!
```js
const model = new ChatAnthropic({
  modelName: "claude-3-haiku-20240307",
  temperature: 0,
  clientOptions: {
    dangerouslyAllowBrowser: true,
  }
});
```
Also, I saw that in other lib, like in openai and groq, we're mandating it to allow browser by default, should we implement the same in anthropic as well?

#### Meta
- [anthropic-sdk-typescript CHANGELOG](https://github.com/anthropics/anthropic-sdk-typescript/blob/main/CHANGELOG.md)
- [Link to issue in upstream](https://github.com/anthropics/anthropic-sdk-typescript/issues/248)
- [Blog on dangerouslyAllowBrowser in upstream sdk](https://simonwillison.net/2024/Aug/23/anthropic-dangerous-direct-browser-access/)

Fixes #6662

### CODE REVIEW

**Comment by rootCircle** [comment]
In other libs like of groq & openai have `dangerouslyAllowBrowser` set to true by default! Should we have the same behavior in this as well?

```diff
diff --git a/libs/langchain-anthropic/src/chat_models.ts b/libs/lan
gchain-anthropic/src/chat_models.ts
index 1e8853ff5..fd659654a 100644
--- a/libs/langchain-anthropic/src/chat_models.ts
+++ b/libs/langchain-anthropic/src/chat_models.ts
@@ -661,7 +661,12 @@ export class ChatAnthropicMessages<
 
     this.createClient =
       fields?.createClient ??
-      ((options: ClientOptions) => new Anthropic(options));
+      ((options: ClientOptions) => {
+        new Anthropic({
+          dangerouslyAllowBrowser: true,
+          ...options,
+        })
+      });
   }
```

**Comment by ricklamers** [comment]
What a coincidence, I am now at a hackathon and needed this 🤯

**Comment by haouarihk** [comment]
when is this getting merged

**Comment by jacoblee93** [comment]
Today sorry all!

**Comment by jacoblee93** [comment]
Thank you! Cutting a release now.

**Comment by jacoblee93** [comment]
Live in @langchain/anthropic@0.3.1! Thanks again!

**Comment by rootCircle** [comment]
Thanks! It was fun contributing for a feature, which even I wanted to use! Thanks @jacoblee93 😊

**Pull request merged**
