### PR TITLE
docs[minor]: Show last update

### PR DESCRIPTION
**Pull request by bracesproul**

### CODE REVIEW

**Comment by jacoblee93** [comment]
Can you pull and run `yarn format`?

**Comment by jacoblee93** [comment]
They all say April 18th?

Should we delay until the next iteration of the docs?

**Comment by bracesproul** [comment]
Closing until a better solution can be found. Current issue: Non authenticated gh api requests hit rate limits pretty quick

**Comment by bracesproul** [comment]
Closing until a better solution can be found. Current issue: Non authenticated gh api requests hit rate limits pretty quick

**Pull request closed without merging**
