### PR TITLE
fix: Add back Chaindesk retriever

### PR DESCRIPTION
**Pull request by gmpetrov**

### CODE REVIEW

**Comment by gmpetrov** [comment]
Why was the Chaindesk retriever removed from the LangchainJS package?

**Comment by jacoblee93** [comment]
Thank you! Removed the old Databerry docs and marked it as deprecated.

**Comment by jacoblee93** [comment]
> Why was the Chaindesk retriever removed from the LangchainJS package?

I don't think it was ever merged:

https://github.com/langchain-ai/langchainjs/pull/1837

**Comment by jacoblee93** [comment]
Thanks for your patience!

**Pull request merged**
