### PR TITLE
feat: serpapi returns list of links

### PR DESCRIPTION
**Pull request by jacobrosenthal**
Not sure if back compat matters but this pairs with webbrowser really well

### CODE REVIEW

**Comment by nfcampos** [comment]
Can we put this behind a constructor arg? That way it will be backwards compatible

**Comment by jacobrosenthal** [comment]
Yeah whatever you decide. I realized Ive also never seen any of those other fields in my searches, so the if case that always hits is the last, which give 1 link.

So this way if it falls through you get all links as well

**Comment by jacobrosenthal** [comment]
Actually I think the returning n links always is a proper fix, the input args allow you to specify how many links you want back, so the code wasnt respecting the inputs before.

**Comment by bracesproul** [comment]
@jacobrosenthal going to close due to merge conflicts. If you'd still like to get this merged in, please open off of an up-to-date main branch, and I'll review. Thank you!

**Pull request closed without merging**
