### PR TITLE
Update runnable config ensure and merge to match py

### PR DESCRIPTION
**Pull request by nfcampos**
- merge now supports merging many configs
- fix issues in edge cases of merge
- call ensure everywhere configs are used
- ensure assigns primitive configurable keys to tracer metadata

Fixes # (issue)

### CODE REVIEW

**Comment by jacoblee93** [comment]
Seems fine, but we don't need to do this in places like here to set defaults?

https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/language_models/chat_models.ts#L139

**Comment by jacoblee93** [comment]
Test might be a flake, can't repro locally

**Comment by nfcampos** [comment]
@jacoblee93 yes but it is also called inside that _split method so technically we already are doing so

**Comment by jacoblee93** [comment]
Thanks!

**Pull request merged**
