### PR TITLE
core[patch]: Passing the input object to the Retry Attempt Handler.

### PR DESCRIPTION
**Pull request by mauriciocirelli**
Hi,

This is related to the following discussion: [How to capture and use the exception error on a Runnable With Retry Chain?](https://github.com/langchain-ai/langchainjs/discussions/5065).

Passing the input object to the retry attempt handler allows the developer to change it with the error information, making the chain capable of fixing the error in the next loop. 

Retrying without fixing the error is very limited.. sometimes retrying the same calls would fix the issue, but usually, it doesnt.

Something like this would do the job:

```typescript
RunnablePassthrough.assign({ 
  results: RunnableSequence.from([
	RunnablePassthrough.assign({ 
	  question: RunnableBranch.from([
		[
		  (input: any) => (input.error),
		  (input: any) => fix_errors(input.question, input.error),
		],
		(input: any) => input.question,
	  ]),
	}),
	RunnablePassthrough.assign({
	  // Clears the error
	  error: () => null,
	}),
	(input: any) => run_may_throw(input.question),
  ])
  .withRetry({
	onFailedAttempt: (error: any, input: any) => {
	  input.error = error.message;
	},
	stopAfterAttempt: 3,
  }),
})
```

The only thing that I would like to improve here is the ```async _batch<ReturnExceptions extends boolean = false>(
    inputs: RunInput[],
    configs?: RunnableConfig[],
    runManagers?: (CallbackManagerForChainRun | undefined)[],
    batchOptions?: RunnableBatchOptions)``` call (line 1375):

```typescript
{
  onFailedAttempt: (error: any) => this.onFailedAttempt(error, inputs),
  retries: Math.max(this.maxAttemptNumber - 1, 0),
  randomize: true,
}
```

Is there a way to capture just the input that caused the exception? I am working around it passing the whole ```inputs``` array, but I think it would be nicer to just pass the faulty one.

I hope this interests the community.

Thank you.

### CODE REVIEW

**Comment by mauriciocirelli** [comment]
Hi, @jacoblee93 

Any chance to have a look into this so we can get it merged?

Thank you!

**Comment by jacoblee93** [comment]
Sorry for the delay! Looking now!

**Comment by jacoblee93** [comment]
Hey @mauriciocirelli, does it make sense to pass the entire input back for `batch`? Feels like it'd make more sense to just pass back the first failure?

**Comment by mauriciocirelli** [comment]
> Hey @mauriciocirelli, does it make sense to pass the entire input back for `batch`? Feels like it'd make more sense to just pass back the first failure?

Not at all.
That's where I get a bit lost on the code... I totally aggree that we should pass just the input that caused the exception, but I could not find a way to do it.

**Comment by jacoblee93** [comment]
What about just setting it on the thrown error:

```ts
          let firstException;
          for (let i = 0; i < results.length; i += 1) {
            const result = results[i];
            const resultMapIndex = remainingIndexes[i];
            // eslint-disable-next-line no-instanceof/no-instanceof
            if (result instanceof Error) {
              if (firstException === undefined) {
                firstException = result;
                (firstException as any).input = foo
              }
            }
            resultsMap[resultMapIndex.toString()] = result;
          }
          if (firstException) {
            throw firstException;
          }
```

**Comment by mauriciocirelli** [comment]
Sounds good.



> What about just setting it on the thrown error:
> 
> ```ts
>           let firstException;
>           for (let i = 0; i < results.length; i += 1) {
>             const result = results[i];
>             const resultMapIndex = remainingIndexes[i];
>             // eslint-disable-next-line no-instanceof/no-instanceof
>             if (result instanceof Error) {
>               if (firstException === undefined) {
>                 firstException = result;
>                 (firstException as any).input = foo
>               }
>             }
>             resultsMap[resultMapIndex.toString()] = result;
>           }
>           if (firstException) {
>             throw firstException;
>           }
> ```

Sounds good.

Have just pushed the changes.

**Comment by jacoblee93** [comment]
LGTM just fix test case

**Comment by mauriciocirelli** [comment]
> LGTM just fix test case

My bad. Looking into it.

**Comment by jacoblee93** [comment]
And run `yarn format` too please!

**Comment by mauriciocirelli** [comment]
> And run `yarn format` too please!

Yeah. I have seen that workflow failing too.
Just pushed.

**Comment by jacoblee93** [comment]
Thank you!

**Comment by mauriciocirelli** [comment]
> Thank you!

Im happy to contribute. Like this kind of PR, that helps making (mine and others) code cleaner.
Thank you for your time looking into it.

**Comment by jacoblee93** [comment]
Getting:

```
1371:36  error  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
```

Can fix myself in a bit

**Comment by mauriciocirelli** [comment]
> Getting:
> 
> ```
> 1371:36  error  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
> ```
> 
> Can fix myself in a bit

I am waiting for everything to finish so I can push it... do not worry.

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
