### PR TITLE
aws[patch]: Fix empty content bug

### LINKED ISSUE #5960: Issue with ChatBedrockConverse and Bedrock Claude Model: ValidationException on Blank Text Field
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
import {RunnableConfig} from '@langchain/core/runnables'
import {ChatBedrockConverse} from '@langchain/aws'

interface ChatState {
  messages: BaseMessage[]
  sourceDocuments: DocumentInterface[]
}

 const model = new ChatBedrockConverse({
          model: "anthropic.claude-3-sonnet-20240229-v1:0"
          region: this.aws_region,
          credentials: credentialsProvider,
          maxTokens: 2500,
          temperature: 0.05
          })

  private async agentNode(
    state: ChatState,
    config?: RunnableConfig
  ): Promise<Partial<ChatState>> {
    const tools = [retrieverTool]
    const model = model.bindTools(tools)

    const response = await model.invoke(state.messages, config)
    logger.debug(`Model response: ${JSON.stringify(response)}`)

    return {messages: [response]}
  }
  ```
  
Maybe any example from [LanggraphJS Examples](https://github.com/langchain-ai/langgraphjs/tree/main/examples) that uses tools, but with "ChatBedrockConverse" and model "anthropic.claude-3-sonnet-20240229-v1:0"?

### Error Message and Stack Trace (if applicable)

Error in CompletionController.generateCompletion() The text field in the ContentBlock object at messages.1.content.0 is blank. Add text to the text field, and try again.","name":"ValidationException","stack":"ValidationException: The text field in the ContentBlock object at messages.1.content.0 is blank. Add text to the text field, and try again.\n    at de_ValidationExceptionRes (/Users/test/code/bot/node_modules/.pnpm/@aws-sdk+client-bedrock-runtime@3.606.0/node_modules/@aws-sdk/client-bedrock-runtime/dist-cjs/index.js:1082:21)\n    at de_CommandError (/Users/test/code/bot/node_modules/.pnpm/@aws-sdk+client-bedrock-runtime@3.606.0/node_modules/@aws-sdk/client-bedrock-runtime/dist-cjs/index.js:937:19)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /Users/test/code/bot/node_modules/.pnpm/@smithy+middleware-serde@3.0.3/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20\n    at async /Users/test/code/bot/node_modules/.pnpm/@smithy+core@2.2.4/node_modules/@smithy/core/dist-cjs/index.js:165:18\n    at async /Users/test/code/bot/node_modules/.pnpm/@smithy+middleware-retry@3.0.7/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38\n    at async /Users/test/code/bot/node_modules/.pnpm/@aws-sdk+middleware-logger@3.598.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22\n    at async ChatBedrockConverse._generateNonStreaming (/Users/test/code/bot/node_modules/.pnpm/@langchain+aws@0.0.1_@aws-sdk+client-sso-oidc@3.606.0_@aws-sdk+client-sts@3.606.0__@aws-sdk+c_wops3cctew2kpyygicqzgjk7su/node_modules/@langchain/aws/dist/chat_models.cjs:222:26)\n    at async Promise.allSettled (index 0)\n    at async ChatBedrockConverse._generateUncached (/Users/test/code/bot/node_modules/.pnpm/@langchain+core@0.2.12_langchain@0.2.8_@aws-sdk+credential-provider-node@3.600.0_@aws-sdk+cli_6wi7pugnjf7kzne7hkijzr5xv4/node_modules/@langchain/core/dist/language_models/chat_models.cjs:177:29)","timestamp":"2024-07-02T13:59:04.567Z

### Description

I'm encountering an issue when invoking the Bedrock Claude model via the Converse API using LangChain's `ChatBedrockConverse`. The error message is:
```
ValidationException: The text field in the ContentBlock object at messages.1.content.0 is blank. Add text to the text field, and try again.
```
This issue does not occur when using `ChatOpenAI` or `BedrockChat`. It seems specific to `ChatBedrockConverse`.

**Steps to Reproduce:**
1. Use Langchain/Langgraph to create a conversation with the Bedrock Claude model via the Converse API.
2. Implement a flow that involves tool usage, leading to empty content messages.
3. Observe the error: `ValidationException` due to a blank `text` field in the `ContentBlock` object.

**Expected Behavior:**
The model should handle tool usage without resulting in empty content messages, or the API should handle such cases gracefully - which I know it's not with Langchain.

**Actual Behavior:**
The process fails with a `ValidationException` when an empty content message is encountered.

**Additional Information:**
- This issue started occurring after upgrading to `ChatBedrockConverse`.
- Manually adding text to the empty content AI messages results in a different error: `The model returned the following errors: Your API request included an 'assistant' message in the final position, which would pre-fill the 'assistant' response. When using tools, pre-filling the 'assistant' response is not supported.`

Example AI message with empty content calling a tool:
```json
{
  "AIMessage": {
    "lc_serializable": true,
    "lc_kwargs": {
      "content": "",
      "tool_calls": [{ "id": "tooluse_e68eeY31Rju83TWq5n-e1A", "name": "retrieve_internal_documents", "args": {}}],
      "response_metadata": {
        "$metadata": { "httpStatusCode": 200, "requestId": "fba07d1c-cfda-4609-a603-ad589da3374a", "attempts": 1, "totalRetryDelay": 0 },
        "metrics": { "latencyMs": 1718 },
        "stopReason": "tool_use",
        "usage": { "inputTokens": 446, "outputTokens": 56, "totalTokens": 502 }
      },
      "usage_metadata": { "input_tokens": 446, "output_tokens": 56, "total_tokens": 502 },
      "id": "fba07d1c-cfda-4609-a603-ad589da3374a",
      "invalid_tool_calls": [],
      "additional_kwargs": {}
    }
  }
}
```

PS: If you feel this issue might be better shared with the LangGraph JS maintainers or if it involves specific nuances of the AWS Bedrock Converse API, please let me know. I initially reported it here since ChatBedrockConverse is hosted within LangChain.

### System Info

```
$ pnpm info langchain

langchain@0.2.8 | MIT | deps: 16 | versions: 280
Typescript bindings for langchain
https://github.com/langchain-ai/langchainjs/tree/main/langchain/

keywords: llm, ai, gpt3, chain, prompt, prompt engineering, chatgpt, machine learning, ml, openai, embeddings, vectorstores

dist
.tarball: https://<internal-proxy>/langchain/-/langchain-0.2.8.tgz
.shasum: 9bd77f5c12071d0ccb637c04fc33415e5369e5aa
.integrity: sha512-kb2IOMA71xH8e6EXFg0l4S+QSMC/c796pj1+7mPBkR91HHwoyHZhFRrBaZv4tV+Td+Ba91J2uEDBmySklZLpNQ==

dependencies:
@langchain/core: >=0.2.9 <0.3.0   js-tiktoken: ^1.0.12              langsmith: ~0.1.30                uuid: ^9.0.0
@langchain/openai: >=0.1.0 <0.3.0 js-yaml: ^4.1.0                   ml-distance: ^4.0.0               yaml: ^2.2.1
@langchain/textsplitters: ~0.0.0  jsonpointer: ^5.0.1               openapi-types: ^12.1.3            zod-to-json-schema: ^3.22.3
binary-extensions: ^2.2.0         langchainhub: ~0.0.8              p-retry: 4                        zod: ^3.22.4

maintainers:
- nfcampos <nuno@boringbits.io>
- jacoblee93 <jacoblee93@gmail.com>
- andrewnguonly <andrewnguonly@gmail.com>
- davidduong <david@duong.cz>
- hwchase17 <hw.chase.17@gmail.com>
- basproul <braceasproul@gmail.com>

dist-tags:
latest: 0.2.8     next: 0.2.3-rc.0

published 4 days ago by basproul <braceasproul@gmail.com>
```

- platform: Mac arm64
- Node version: v20.15.0
- yarn version: N/A (ppm version: 9.4.0)

### PR DESCRIPTION
**Pull request by bracesproul**
Closes #5960

Fixes bug where messages with empty string contents were being passed to the Bedrock Converse API.

Added test for e2e use case, and test for the message converter util

### CODE REVIEW

**Comment by tinque** [comment]
Hello @bracesproul,

Do you know when this should be released?

Thanks

**Comment by bracesproul** [comment]
@tinque Planning on releasing this today

**Comment by MarcoLooy** [comment]
@bracesproul  super cool. Thanks a lot for fixing the issue, very much appreciated!

**Comment by jvjfranca-auramind** [comment]
Hi! Is this fixed for python as well?
Best regards!

**Pull request merged**
