### PR TITLE
community[patch]: Add `keep_alive` parameter to Ollama API.

### PR DESCRIPTION
**Pull request by andrewnguonly**
Fixes # https://github.com/langchain-ai/langchainjs/issues/4282

### CODE REVIEW

**Comment by jacoblee93** [comment]
Thanks for this!

Would it make more sense to queue up a `langchain-ollama` integration package that wraps their new SDK directly and try to get that in sometime in the next few days?

**Comment by alvarosevilla95** [comment]
> Thanks for this!
> 
> Would it make more sense to queue up a `langchain-ollama` integration package that wraps their new SDK directly and try to get that in sometime in the next few days?

Just 2 cents from a random user, but I was looking forward to seeing this added. While a full integration with their SDK sounds ideal, if this could be merged now rather than wait on that I would greatly apprecieate it.

**Comment by jacoblee93** [comment]
@andrewnguonly yes I think @alvarosevilla95 is right in that this should be added to the chat model and embedding class as well.

As for what makes a partner package - deps are a big part of it, yes. Community has a ton of peer deps that can cause incidental issues due to the way that npm handles peer dependency conflicts, and we can version breaking SDK changes more intelligently with an integration package.

I could timebox a new package to today and if I run into difficulty, I could merge this one and #4466 instead and release it if that sounds good?

**Comment by jacoblee93** [comment]
Ok, sounds like it's Node only for a little while longer - let's merge these! Will get it in by the end of the day.

**Comment by jacoblee93** [comment]
Thank you!

**Comment by jacoblee93** [comment]
This and #4466 are live in the latest community release! Stay tuned for a separate Ollama package

**Pull request merged**
