### PR TITLE
Use replaceAll instead of replace when generating operationid.

### LINKED ISSUE #3266: Conversion issue in `createOpenAPIChain`?
Looks like there's an unexpected `.` in the API function name somehow, can't trace down where the `.` -> `_` replacement is supposed to be happening in langchainjs.

```
[llm/error] [1:llm:ChatOpenAI] [2.18s] LLM run errored with error: "400 '_api_v1_0.0/weather_get' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'functions.0.name'"
A promise rejection was handled asynchronously. This warning occurs when attaching a catch handler to a promise after it rejected. (rejection #3)
[mf:err] Error: 400 '_api_v1_0.0/weather_get' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'functions.0.name'
    at APIError.generate (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/openai/src/error.ts:66:14)
    at OpenAI.makeStatusError (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/openai/src/core.ts:358:21)
    at OpenAI.makeRequest (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/openai/src/core.ts:416:24)
    at null.<anonymous> (async index.js:18794:25)
    at async RetryOperation._fn (/Users/dave/Work/langchain-workers/langchain-worker/node_modules/p-retry/index.js:50:12)
```

Code to reproduce:

```typescript
const chain = await createOpenAPIChain("https://caymanweather.aimoda.dev/openapi.json", {
  llm: model
});

const result = await chainapi.run(`What's the current weather in Cayman?`);
```

### PR DESCRIPTION
**Pull request by Manouchehri**
Fixes #3266.

### CODE REVIEW

**Comment by jacoblee93** [comment]
Thank you!

**Comment by jacoblee93** [comment]
Can you run `yarn format`?

**Comment by Manouchehri** [comment]
Done!

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
