### PR TITLE
updated weaviate-ts-client to 2.0.0

### PR DESCRIPTION
**Pull request by the-powerpointer**

### CODE REVIEW

**Review by bracesproul — COMMENTED** [review]
What's the reason for the bump?

**Comment by jacoblee93** [comment]
I think the right thing to do here is to separate things out into their own integration package - I can have a look shortly

**Comment by jacoblee93** [comment]
You can now use this new version via `@langchain/weaviate`: https://www.npmjs.com/package/@langchain/weaviate

**Comment by the-powerpointer** [comment]
@jacoblee93 Thank you for this. However, I still don't get how to use this correctly.
I've tried all combinations of `@langchain/weaviate` and `weaviate-ts-client` dependencies: different versions, with or without explicit `weaviate-ts-client` dependency. I can't get it to work.

I need to create a `WeaviateClient` and assign it to a `WeaviateStore`. For this I have imports 
```
import weaviate, { WeaviateClient } from 'weaviate-ts-client';
import { WeaviateStore } from '@langchain/weaviate';
```
with later usage:
```
this.weaviateClient = weaviate.client({
  scheme: this.protocol,
  host: this.host,
  apiKey: new weaviate.ApiKey(this.apiKey)
});

this.store = new WeaviateStore(model, {
  client: this.weaviateClient,
  indexName: this.indexName
});
```
When I only add dependency `@langchain/weaviate (v0.0.1)`, then I rely on the dependency `weaviate-ts-client (v1.4.0)`, which is delivered with `langchain (v0.1.20)`. However, `@langchain/weaviate (v0.0.1)` uses `weaviate-ts-client (v2.0.0)`. So the type of the client I construct, comes from `weaviate-ts-client (v1.4.0)`, but the store requires a client from `weaviate-ts-client (v2.0.0)`, and the types don't match.

When I further try to add dependency `weaviate-ts-client (v2.0.0)` directly, I get peer dependency errors at `npm install`:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: langchain@0.1.20
npm ERR! Found: weaviate-ts-client@2.0.0
npm ERR! node_modules/weaviate-ts-client
npm ERR!   weaviate-ts-client@"2.0.0" from the root project
npm ERR!   weaviate-ts-client@"^2.0.0" from @langchain/weaviate@0.0.1
npm ERR!   node_modules/@langchain/weaviate
npm ERR!     @langchain/weaviate@"0.0.1" from the root project
npm ERR!   1 more (@langchain/community)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional weaviate-ts-client@"^1.4.0" from langchain@0.1.20
npm ERR! node_modules/langchain
npm ERR!   langchain@"0.1.20" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: weaviate-ts-client@1.6.0
npm ERR! node_modules/weaviate-ts-client
npm ERR!   peerOptional weaviate-ts-client@"^1.4.0" from langchain@0.1.20
npm ERR!   node_modules/langchain
npm ERR!     langchain@"0.1.20" from the root project
...
```

In my opinion the `@langchain/weaviate` package is not compatible with what `langchain` package currently provides.
What I'm doing wrong?

**Comment by jacoblee93** [comment]
Can you update your LangChain version? Old versions will still have a peer dep set, new ones will not:

https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-community/package.json#L254

**Comment by the-powerpointer** [comment]
If I understood correctly, the langchain repo is still in a transition phase where not all code has been moved to some "integration" package?
I rely on classes like `GithubRepoLoader` or `TextSplitter`, which I have not found to be moved to one of the new `@langchain/...` packages.
So I have to use the `langchain` package, which (in current version 0.1.20) still points to 1.4.0 ([devDependencies](https://github.com/langchain-ai/langchainjs/blob/main/langchain/package.json#L1297), [peerDependencies](https://github.com/langchain-ai/langchainjs/blob/main/langchain/package.json#L1350)).

**Comment by jacoblee93** [comment]
Some code will stay in `langchain`!

And yes, that's correct. Depending on what version you're currently on, you may be able to bump the initial `@langchain/community`version instead

**Comment by the-powerpointer** [comment]
Okay, I now have added `@langchain/community (v0.0.31)` explicitly to have the latest version.
The relevant dependencies from my package.json:
```
  "dependencies": {
    ...
    "@langchain/community": "0.0.31",
    "@langchain/openai": "0.0.14",
    "@langchain/weaviate": "0.0.1",
    "langchain": "0.1.20",
    ...
```
With this (explicitly no `weaviate-ts-client` package added) I still have the compile errors about mismatching types:
```
TS2375: Type
import('C:/Users/the-powerpointer/git/gpt-for-documentation/data-loader/node_modules/weaviate-ts-client/dist/index').WeaviateClient
is not assignable to type
import('C:/Users/the-powerpointer/git/gpt-for-documentation/data-loader/node_modules/@langchain/weaviate/node_modules/weaviate-ts-client/dist/index').WeaviateClient
with 'exactOptionalPropertyTypes: true'. Consider adding undefined to the types of the target's properties.
The types returned by graphql.get() are incompatible between these types.
Type 'import("C:/Users/the-powerpointer/git/gpt-for-documentation/data-loader/node_modules/weaviate-ts-client/dist/index").GraphQLGetter' is not assignable to type 'import("C:/Users/the-powerpointer/git/gpt-for-documentation/data-loader/node_modules/@langchain/weaviate/node_modules/weaviate-ts-client/dist/index").GraphQLGetter'.
Types have separate declarations of a private property after
vectorstores.d.ts(12, 5): The expected type comes from property client which is declared here on type WeaviateLibArgs
```
When trying to add `weaviate-ts-client v2.0.0` package, I get the same peer dependency errors:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: langchain@0.1.20
npm ERR! Found: weaviate-ts-client@2.0.0
npm ERR! node_modules/weaviate-ts-client
npm ERR!   weaviate-ts-client@"2.0.0" from the root project
npm ERR!   peerOptional weaviate-ts-client@"*" from @langchain/community@0.0.31
npm ERR!   node_modules/@langchain/community
npm ERR!     @langchain/community@"0.0.31" from the root project
npm ERR!     @langchain/community@"~0.0.29" from langchain@0.1.20
npm ERR!     node_modules/langchain
npm ERR!       langchain@"0.1.20" from the root project
npm ERR!   1 more (@langchain/weaviate)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional weaviate-ts-client@"^1.4.0" from langchain@0.1.20
npm ERR! node_modules/langchain
npm ERR!   langchain@"0.1.20" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: weaviate-ts-client@1.6.0
npm ERR! node_modules/weaviate-ts-client
npm ERR!   peerOptional weaviate-ts-client@"^1.4.0" from langchain@0.1.20
npm ERR!   node_modules/langchain
npm ERR!     langchain@"0.1.20" from the root project
```

Sorry, I feel a little stupid, but I don't know how to solve this.

**Comment by jacoblee93** [comment]
Oh my god we're silly and forgot to update the peer dep on `langchain/package.json` - will patch!

This is the offending line:

https://github.com/langchain-ai/langchainjs/blob/main/langchain/package.json#L1350

We also generally recommend using `yarn` or `pnpm` for their saner peer dep resolution rules if possible.

**Comment by jacoblee93** [comment]
Just opened #4475

**Comment by the-powerpointer** [comment]
Thank you for this!
Then I'll wait for the next release and try again. I will comment here then.
I'll have a look at the alternative package managers. Thank you.

**Comment by jacoblee93** [comment]
Relaxed peer dep is live in latest langchain!

**Comment by the-powerpointer** [comment]
Finally! Works like a charm. Thank you very much.
This solved the frustration of one day 😏

**Comment by jacoblee93** [comment]
Thank you for your patience!

**Pull request closed without merging**
