### PR TITLE
community[major]: Jacob/gemini

### PR DESCRIPTION
**Pull request by jacoblee93**
Extends #3621, split into separate package. Will give a more thorough review tomorrow.

CC @alx13

### CODE REVIEW

**Comment by alx13** [comment]
Please don't merge it yet, I'll update my branch first with some cleanup, examples and test by EOD today.

**Comment by danny-avila** [comment]
Great work! Didn't expect to see integration so soon

**Comment by jacoblee93** [comment]
> Please don't merge it yet, I'll update my branch first with some cleanup, examples and test by EOD today.

Ok, I've pushed some updates here as well @alx13 - feel free to merge back into yours.

**Comment by jacoblee93** [comment]
@alx13 ready for you! Added some more tests and found a small off-by-one in the system message hack. 

Could you fill in the `// Docs here` sections of the docs with signup/other relevant getting started info?

LMK if you have any feedback - excited to get this out!

**Comment by jacoblee93** [comment]
Closing in favor of #3621!

**Pull request closed without merging**
