### PR TITLE
LLMonitor Callback Handler: support for future OpenAI kwargs

### PR DESCRIPTION
**Pull request by vincelwt**
Hi, 
This ensures support for future OpenAI kwargs (tools, tool_calls, etc.) ensuring maximum compatibility.

### CODE REVIEW

**Comment by jacoblee93** [comment]
Thank you!

**Comment by jacoblee93** [comment]
Ah actually you will need to run `yarn` to update the lockfile if you don't mind

**Comment by vincelwt** [comment]
@jacoblee93 Done + some other improvements, thank you!

**Comment by jacoblee93** [comment]
Seems like there's some TypeScript issue now:

Screenshot 2023-11-10 at 12 35 59 PM

**Comment by vincelwt** [comment]
Hi @jacoblee93 it should be fixed, I'm not seeing the `test-exports` CI results though 🤔

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
